# Playing Nicely With Others
## Work in Progress

So far, we've gotten ourselves to a point where we can explore our data, perform some analyses, and graph our results intelligently. That's all great, and are incredibly important skills. However, even more important than the hard coding skills we've been building is the ability to communicate our results - to our peers, bosses, and the larger outside world.

We'll be using a lot of non-R technologies this unit, and focusing mostly on how to use these technologies in a workflow that resembles those used in the modern scientific world. Plenty of scientists don't use R Markdown. Even more don't use Git. Some may have never heard of LaTeX. But these are skills and tools which are growing in importance and acceptance throughout the scientific community, so getting used to them now will make your life significantly better. But even moreso than that, understanding how to learn tools like these - at least to the depths you need them - will help you pick up new tools and tech as the world continues to advance. We aren't going super deep into any tool - but we'll go deep enough to make their benefits obvious.

## R Markdown
The Markdown programming language was developed in 2004 to let developers write HTML in a way that is human-readable and easily writeable. R Markdown is an implementation of that language in R, which 

### Kable

## Latex

## Git(hub)
Git is a version control system originally developed in 2005 to let a lot of extremely talented coders work together on one of the largest, most complex open source projects the world has ever seen. It is a nightmare to learn, and every company does it slightly differently.

GitHub is a company founded in 2008, designed to provide streamlined servers and plugins to allow teams and non-professionals to use Git on various projects. The tools it provides are less powerful than Git itself, but much faster to learn.

For that reason, we'll be using GitHub - and the tools developed specifically for using Git with GitHub - exclusively in this unit. There's really no reason to learn Git by itself right now; it's a good skill to pick up eventually, but not while busy learning another computer language. If you're interested in a tutorial written specifically for Git, check out [this blog](http://kbroman.org/github_tutorial/) by Karl Broman.

## Commenting Code

https://uc3.cdlib.org/2014/05/05/github-a-primer-for-researchers/