# Changelog

## Version 1.0.2
Released

* Edits to chapter 3 (Workflow), increasing coverage of `tidyr` functions
* Edits to chapter 4 (EDA), adding cross validation and confusion matrices
* Split chapter 3 into two (Workflow/Wrangling), because those are different topics and these aren't course notes anymore, so relatedness matters more than each unit being similar length. That said, I want the Workflow chapter to be longer or rolled into another unit, so we'll see how that lasts.
* Restructured chapters on Wrangling, EDA, and "More Complex Analyses" to now more tighly match the data analysis pipeline model - now form the Wrangling-EDA-Model chapters.
* Reordered chapters - stats to the end as a glossary, and others shifted to make room for the pipeline model in the middle.
* Slowly changing some just bizarre markdown syntax I was using (three graves for in-line code, for instance)
* Added parts worth saving of cut chapters into chapter 5. I'm planning on retooling this entire chapter - making it an introduction to modeling concepts, with the gapminder exercise moved to the end as a lab - but that's beyond me right now.

## Version 1.0.1
Released 2019-04-01 (no joke!)

* Added "State of the Book" disclaimer to the introduction, as changes are being made
* Changed references to "course" and "reader" to "book", reflecting new purpose of document
* Deleted 12: Machine Learning and 11: Specialized Applications, with intents to roll the relevant pieces into EDA and MCA
* Split chapter 1 into two (Introduction/Data Viz) due to length; this made every chapter number change
* Edits to chapter 1, chapter 2

## Version 1.0.0
This is the build I started tracking changes from, last updated 2019-01-24. At this point, the book had 12 chapters, as well as an FAQ and list of resources. 