---
title: "Introduction to Data Exploration and Analysis with R"
author: "Michael Mahoney"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
bookdown::gitbook:
  config:
    toc:
      collapse: section
      scroll_highlight: yes
    toolbar:
      position: fixed
    edit : null
    download: null
    search: yes
    fontsettings:
      theme: white
      family: sans
      size: 2
toc_float: true
documentclass: book
github-repo: MikeMahoney218/LectureBook
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Welcome to IDEAR {-}

> There are only two kinds of programming languages: those people always bitch about and those nobody uses.  
> --- Bjarne Stroustrup  

>Figures often beguile me, particularly when I have the arranging of them myself; in which case the remark attributed to Disraeli would often apply with justice and force: 'There are three kinds of lies: lies, damned lies, and statistics.  
> --- Mark Twain

This is a course reader for a class that will never be taught. Hopefully it helps you nonetheless.

Much of this reader draws from Hadley Wickham's 2012 [stat405](http://stat405.had.co.nz/) class, as well as his wonderful textbooks [R for Data Science](http://r4ds.had.co.nz/index.html) (with Garrett Grolemund) and [Advanced R](https://adv-r.hadley.nz/index.html). Additional steering comes from the [YaRrr!](https://bookdown.org/ndphillips/YaRrr/) textbook. I've updated some elements, distilled others, and not kept much of the content, but the ideas and steering come very directly from those works.

This course serves as an introduction to R for scientific and research applications, focusing specifically on exploratory data analysis, hypothesis generation and confirmation, data visualization, and communication of results. It is not an introduction to statistics course, though it will teach some statistics. It isn't even an introduction to computer programming or computer science course, though it will teach some of each of those. 

This reader is currently being continuously deployed to  [bookdown.org](https://bookdown.org/connect/#/apps/2008/access) and [GitHub](https://github.com/mikemahoney218/Intro_to_R_Reader), particularly as new sections are completed or old ones restructured. This is so that I can get feedback from the small group of people who are using this book to learn R themselves, so I can adjust and adapt the text as needed. If you'd like to help with this process, I'd love to hear from you, at <mike.mahoney.218@gmail.com>, or see a pull request made on GitHub. More information about me can be found at [my website](https://www.mikemahoney218.com), which just so happens to have been built in R.

Units 1-5 are currently complete. In production are units 6 and 7 - you can see the skeletons forming at the bottom of this document. There are currently 11 units planned.