<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>6 Modeling Data | Introduction to Data Exploration and Analysis with R</title>
  <meta name="description" content="A detailed introduction to coding in R and the process of data analytics. Version 1.0.0">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="6 Modeling Data | Introduction to Data Exploration and Analysis with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A detailed introduction to coding in R and the process of data analytics. Version 1.0.0" />
  <meta name="github-repo" content="MikeMahoney218/Intro_to_R_Reader" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Modeling Data | Introduction to Data Exploration and Analysis with R" />
  
  <meta name="twitter:description" content="A detailed introduction to coding in R and the process of data analytics. Version 1.0.0" />
  

<meta name="author" content="Michael Mahoney">


<meta name="date" content="2019-06-27">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="introduction-to-data-analysis.html">
<link rel="next" href="achieving-graphical-excellence.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.2/leaflet.js"></script>
<link href="libs/leaflet-awesomemarkers-2.0.3/leaflet.awesome-markers.css" rel="stylesheet" />
<script src="libs/leaflet-awesomemarkers-2.0.3/leaflet.awesome-markers.min.js"></script>
<link href="libs/fontawesome-4.7.0/font-awesome.min.css" rel="stylesheet" />


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to IDEAR</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#the-state-of-the-book"><i class="fa fa-check"></i><b>0.1</b> The State of the Book</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#book-outline"><i class="fa fa-check"></i><b>0.2</b> Book Outline</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#other-sources"><i class="fa fa-check"></i><b>0.3</b> Other Sources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#why-does-this-book-exist"><i class="fa fa-check"></i><b>1.1</b> Why Does This Book Exist?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#what-is-r"><i class="fa fa-check"></i><b>1.2</b> What is R?</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#what-is-coding"><i class="fa fa-check"></i><b>1.3</b> What is coding?</a></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#conventions-of-the-book"><i class="fa fa-check"></i><b>1.4</b> Conventions of the book</a></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#things-youll-need"><i class="fa fa-check"></i><b>1.5</b> Things You’ll Need</a></li>
<li class="chapter" data-level="1.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#introduction-to-rstudio"><i class="fa fa-check"></i><b>1.6</b> Introduction to RStudio</a></li>
<li class="chapter" data-level="1.7" data-path="introduction-to-r.html"><a href="introduction-to-r.html#your-first-program"><i class="fa fa-check"></i><b>1.7</b> Your First Program</a></li>
<li class="chapter" data-level="1.8" data-path="introduction-to-r.html"><a href="introduction-to-r.html#the-iris-dataset"><i class="fa fa-check"></i><b>1.8</b> The iris Dataset</a></li>
<li class="chapter" data-level="1.9" data-path="introduction-to-r.html"><a href="introduction-to-r.html#graphing-with-r"><i class="fa fa-check"></i><b>1.9</b> Graphing with R</a></li>
<li class="chapter" data-level="1.10" data-path="introduction-to-r.html"><a href="introduction-to-r.html#exercises"><i class="fa fa-check"></i><b>1.10</b> Exercises</a><ul>
<li class="chapter" data-level="1.10.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#calculate-the-following"><i class="fa fa-check"></i><b>1.10.1</b> Calculate the following:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html"><i class="fa fa-check"></i><b>2</b> Visualizing Your Data</a><ul>
<li class="chapter" data-level="2.1" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#what-is-a-visualization"><i class="fa fa-check"></i><b>2.1</b> What is a Visualization?</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#the-tidyverse-package"><i class="fa fa-check"></i><b>2.2</b> The Tidyverse Package</a></li>
<li class="chapter" data-level="2.3" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#ggplot2"><i class="fa fa-check"></i><b>2.3</b> ggplot2</a><ul>
<li class="chapter" data-level="2.3.1" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#functions-in-ggplot"><i class="fa fa-check"></i><b>2.3.1</b> Functions in ggplot</a></li>
<li class="chapter" data-level="2.3.2" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#changing-aesthetics"><i class="fa fa-check"></i><b>2.3.2</b> Changing Aesthetics</a></li>
<li class="chapter" data-level="2.3.3" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#facetting"><i class="fa fa-check"></i><b>2.3.3</b> Facetting</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#diamonds"><i class="fa fa-check"></i><b>2.4</b> Diamonds</a><ul>
<li class="chapter" data-level="2.4.1" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#visualizing-large-datasets"><i class="fa fa-check"></i><b>2.4.1</b> Visualizing Large Datasets</a></li>
<li class="chapter" data-level="2.4.2" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#axis-transformations"><i class="fa fa-check"></i><b>2.4.2</b> Axis Transformations</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#other-popular-geoms"><i class="fa fa-check"></i><b>2.5</b> Other Popular Geoms</a><ul>
<li class="chapter" data-level="2.5.1" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#histograms"><i class="fa fa-check"></i><b>2.5.1</b> Histograms</a></li>
<li class="chapter" data-level="2.5.2" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#bar-charts"><i class="fa fa-check"></i><b>2.5.2</b> Bar Charts</a></li>
<li class="chapter" data-level="2.5.3" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#jittered-points"><i class="fa fa-check"></i><b>2.5.3</b> Jittered Points</a></li>
<li class="chapter" data-level="2.5.4" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#boxplot"><i class="fa fa-check"></i><b>2.5.4</b> Boxplot</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#designing-good-graphics"><i class="fa fa-check"></i><b>2.6</b> Designing Good Graphics</a></li>
<li class="chapter" data-level="2.7" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#saving-your-graphics"><i class="fa fa-check"></i><b>2.7</b> Saving Your Graphics</a></li>
<li class="chapter" data-level="2.8" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#more-resources"><i class="fa fa-check"></i><b>2.8</b> More Resources</a></li>
<li class="chapter" data-level="2.9" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#exercises-1"><i class="fa fa-check"></i><b>2.9</b> Exercises</a><ul>
<li class="chapter" data-level="2.9.1" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#graph-the-following"><i class="fa fa-check"></i><b>2.9.1</b> Graph the following:</a></li>
<li class="chapter" data-level="2.9.2" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#use-a-new-dataset"><i class="fa fa-check"></i><b>2.9.2</b> Use a new dataset:</a></li>
<li class="chapter" data-level="2.9.3" data-path="visualizing-your-data.html"><a href="visualizing-your-data.html#looking-ahead"><i class="fa fa-check"></i><b>2.9.3</b> Looking ahead:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html"><i class="fa fa-check"></i><b>3</b> R Functions and Workflow</a><ul>
<li class="chapter" data-level="3.1" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#workflow"><i class="fa fa-check"></i><b>3.1</b> Workflow</a><ul>
<li class="chapter" data-level="3.1.1" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#scripts"><i class="fa fa-check"></i><b>3.1.1</b> Scripts</a></li>
<li class="chapter" data-level="3.1.2" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#notebooks"><i class="fa fa-check"></i><b>3.1.2</b> Notebooks</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#memory-objects-and-names"><i class="fa fa-check"></i><b>3.2</b> Memory, Objects, and Names</a></li>
<li class="chapter" data-level="3.3" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#dataframes"><i class="fa fa-check"></i><b>3.3</b> Dataframes</a></li>
<li class="chapter" data-level="3.4" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#oddballs"><i class="fa fa-check"></i><b>3.4</b> Oddballs</a></li>
<li class="chapter" data-level="3.5" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#r-studio-tips-and-tricks"><i class="fa fa-check"></i><b>3.5</b> R Studio Tips and Tricks</a></li>
<li class="chapter" data-level="3.6" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#r-functions-and-workflow-exercises"><i class="fa fa-check"></i><b>3.6</b> R Functions and Workflow Exercises</a><ul>
<li class="chapter" data-level="3.6.1" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#do-the-following"><i class="fa fa-check"></i><b>3.6.1</b> Do the following:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i><b>4</b> Data Wrangling</a><ul>
<li class="chapter" data-level="4.1" data-path="data-wrangling.html"><a href="data-wrangling.html#thinking-with-data"><i class="fa fa-check"></i><b>4.1</b> Thinking with Data</a></li>
<li class="chapter" data-level="4.2" data-path="data-wrangling.html"><a href="data-wrangling.html#the-data-analytics-model"><i class="fa fa-check"></i><b>4.2</b> The Data Analytics Model</a></li>
<li class="chapter" data-level="4.3" data-path="data-wrangling.html"><a href="data-wrangling.html#wrangle"><i class="fa fa-check"></i><b>4.3</b> Wrangle</a><ul>
<li class="chapter" data-level="4.3.1" data-path="data-wrangling.html"><a href="data-wrangling.html#tidy-data"><i class="fa fa-check"></i><b>4.3.1</b> Tidy Data</a></li>
<li class="chapter" data-level="4.3.2" data-path="data-wrangling.html"><a href="data-wrangling.html#tidying-data"><i class="fa fa-check"></i><b>4.3.2</b> Tidying Data</a></li>
<li class="chapter" data-level="4.3.3" data-path="data-wrangling.html"><a href="data-wrangling.html#separating-values"><i class="fa fa-check"></i><b>4.3.3</b> Separating Values</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="data-wrangling.html"><a href="data-wrangling.html#the-pipe"><i class="fa fa-check"></i><b>4.4</b> The Pipe</a></li>
<li class="chapter" data-level="4.5" data-path="data-wrangling.html"><a href="data-wrangling.html#data-transformations"><i class="fa fa-check"></i><b>4.5</b> Data Transformations</a><ul>
<li class="chapter" data-level="4.5.1" data-path="data-wrangling.html"><a href="data-wrangling.html#mutate"><i class="fa fa-check"></i><b>4.5.1</b> Mutate</a></li>
<li class="chapter" data-level="4.5.2" data-path="data-wrangling.html"><a href="data-wrangling.html#tibbles"><i class="fa fa-check"></i><b>4.5.2</b> Tibbles</a></li>
<li class="chapter" data-level="4.5.3" data-path="data-wrangling.html"><a href="data-wrangling.html#subsetting-data"><i class="fa fa-check"></i><b>4.5.3</b> Subsetting Data</a></li>
<li class="chapter" data-level="4.5.4" data-path="data-wrangling.html"><a href="data-wrangling.html#filtering-with-the-tidyverse"><i class="fa fa-check"></i><b>4.5.4</b> Filtering with the Tidyverse</a></li>
<li class="chapter" data-level="4.5.5" data-path="data-wrangling.html"><a href="data-wrangling.html#working-with-groups"><i class="fa fa-check"></i><b>4.5.5</b> Working with Groups</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="data-wrangling.html"><a href="data-wrangling.html#missing-values"><i class="fa fa-check"></i><b>4.6</b> Missing Values</a><ul>
<li class="chapter" data-level="4.6.1" data-path="data-wrangling.html"><a href="data-wrangling.html#explicit-missing-values"><i class="fa fa-check"></i><b>4.6.1</b> Explicit Missing Values</a></li>
<li class="chapter" data-level="4.6.2" data-path="data-wrangling.html"><a href="data-wrangling.html#implicit-missing-values"><i class="fa fa-check"></i><b>4.6.2</b> Implicit Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="data-wrangling.html"><a href="data-wrangling.html#count-data"><i class="fa fa-check"></i><b>4.7</b> Count Data</a><ul>
<li class="chapter" data-level="4.7.1" data-path="data-wrangling.html"><a href="data-wrangling.html#work-with-other-datasets"><i class="fa fa-check"></i><b>4.7.1</b> Work with other datasets:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html"><i class="fa fa-check"></i><b>5</b> Introduction to Data Analysis</a><ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>5.1</b> Exploratory Data Analysis</a><ul>
<li class="chapter" data-level="5.1.1" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html#sidenote"><i class="fa fa-check"></i><b>5.1.1</b> Sidenote</a></li>
<li class="chapter" data-level="5.1.2" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html#the-eda-framework"><i class="fa fa-check"></i><b>5.1.2</b> The EDA Framework</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html#gapminder"><i class="fa fa-check"></i><b>5.2</b> gapminder</a></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html#summarizing-data"><i class="fa fa-check"></i><b>5.3</b> Summarizing Data</a><ul>
<li class="chapter" data-level="5.3.1" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html#sidenote-1"><i class="fa fa-check"></i><b>5.3.1</b> Sidenote</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html#visualizing-data"><i class="fa fa-check"></i><b>5.4</b> Visualizing Data</a></li>
<li class="chapter" data-level="5.5" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html#analyzing-patterns"><i class="fa fa-check"></i><b>5.5</b> Analyzing Patterns</a></li>
<li class="chapter" data-level="5.6" data-path="introduction-to-data-analysis.html"><a href="introduction-to-data-analysis.html#exercises-2"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modeling-data.html"><a href="modeling-data.html"><i class="fa fa-check"></i><b>6</b> Modeling Data</a><ul>
<li class="chapter" data-level="6.1" data-path="modeling-data.html"><a href="modeling-data.html#why-model"><i class="fa fa-check"></i><b>6.1</b> Why Model?</a></li>
<li class="chapter" data-level="6.2" data-path="modeling-data.html"><a href="modeling-data.html#linear-models"><i class="fa fa-check"></i><b>6.2</b> Linear Models</a></li>
<li class="chapter" data-level="6.3" data-path="modeling-data.html"><a href="modeling-data.html#model-predictions"><i class="fa fa-check"></i><b>6.3</b> Model Predictions</a></li>
<li class="chapter" data-level="6.4" data-path="modeling-data.html"><a href="modeling-data.html#classification"><i class="fa fa-check"></i><b>6.4</b> Classification</a></li>
<li class="chapter" data-level="6.5" data-path="modeling-data.html"><a href="modeling-data.html#logistic-models"><i class="fa fa-check"></i><b>6.5</b> Logistic Models</a></li>
<li class="chapter" data-level="6.6" data-path="modeling-data.html"><a href="modeling-data.html#evaluating-and-comparing-models"><i class="fa fa-check"></i><b>6.6</b> Evaluating and Comparing Models</a><ul>
<li class="chapter" data-level="6.6.1" data-path="modeling-data.html"><a href="modeling-data.html#confusion-matrices"><i class="fa fa-check"></i><b>6.6.1</b> Confusion Matrices</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="modeling-data.html"><a href="modeling-data.html#conclusion"><i class="fa fa-check"></i><b>6.7</b> Conclusion</a></li>
<li class="chapter" data-level="6.8" data-path="modeling-data.html"><a href="modeling-data.html#exercises-3"><i class="fa fa-check"></i><b>6.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html"><i class="fa fa-check"></i><b>7</b> Achieving Graphical Excellence</a><ul>
<li class="chapter" data-level="7.1" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#introduction"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#getting-started"><i class="fa fa-check"></i><b>7.2</b> Getting Started</a></li>
<li class="chapter" data-level="7.3" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#themes"><i class="fa fa-check"></i><b>7.3</b> Themes</a></li>
<li class="chapter" data-level="7.4" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#colors"><i class="fa fa-check"></i><b>7.4</b> Colors</a><ul>
<li class="chapter" data-level="7.4.1" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#viridis"><i class="fa fa-check"></i><b>7.4.1</b> Viridis</a></li>
<li class="chapter" data-level="7.4.2" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#color-brewer"><i class="fa fa-check"></i><b>7.4.2</b> Color Brewer</a></li>
<li class="chapter" data-level="7.4.3" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#other-packages"><i class="fa fa-check"></i><b>7.4.3</b> Other Packages</a></li>
<li class="chapter" data-level="7.4.4" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#making-your-own"><i class="fa fa-check"></i><b>7.4.4</b> Making Your Own</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#labels"><i class="fa fa-check"></i><b>7.5</b> Labels</a></li>
<li class="chapter" data-level="7.6" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#animation"><i class="fa fa-check"></i><b>7.6</b> Animation</a></li>
<li class="chapter" data-level="7.7" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#specialized-visualizations"><i class="fa fa-check"></i><b>7.7</b> Specialized Visualizations</a><ul>
<li class="chapter" data-level="7.7.1" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#stacked-area-plots"><i class="fa fa-check"></i><b>7.7.1</b> Stacked Area Plots</a></li>
<li class="chapter" data-level="7.7.2" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#ggridges"><i class="fa fa-check"></i><b>7.7.2</b> ggridges</a></li>
<li class="chapter" data-level="7.7.3" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#maps"><i class="fa fa-check"></i><b>7.7.3</b> Maps</a></li>
<li class="chapter" data-level="7.7.4" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#circular-charts"><i class="fa fa-check"></i><b>7.7.4</b> Circular Charts</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#rearranging-groups"><i class="fa fa-check"></i><b>7.8</b> Rearranging Groups</a></li>
<li class="chapter" data-level="7.9" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#further-reading"><i class="fa fa-check"></i><b>7.9</b> Further Reading</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html"><i class="fa fa-check"></i><b>8</b> Functions and Scripting</a><ul>
<li class="chapter" data-level="8.1" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#writing-functions"><i class="fa fa-check"></i><b>8.1</b> Writing Functions</a><ul>
<li class="chapter" data-level="8.1.1" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#our-first-function"><i class="fa fa-check"></i><b>8.1.1</b> Our First Function</a></li>
<li class="chapter" data-level="8.1.2" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#returns"><i class="fa fa-check"></i><b>8.1.2</b> Returns</a></li>
<li class="chapter" data-level="8.1.3" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#more-complicated-functions"><i class="fa fa-check"></i><b>8.1.3</b> More Complicated Functions</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#about-names"><i class="fa fa-check"></i><b>8.2</b> About Names…</a></li>
<li class="chapter" data-level="8.3" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#conditional-statements"><i class="fa fa-check"></i><b>8.3</b> Conditional Statements</a></li>
<li class="chapter" data-level="8.4" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#stops"><i class="fa fa-check"></i><b>8.4</b> Stops</a></li>
<li class="chapter" data-level="8.5" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#function-dependencies"><i class="fa fa-check"></i><b>8.5</b> Function Dependencies</a></li>
<li class="chapter" data-level="8.6" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#saving-and-loading-functions"><i class="fa fa-check"></i><b>8.6</b> Saving and Loading Functions</a></li>
<li class="chapter" data-level="8.7" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#loops"><i class="fa fa-check"></i><b>8.7</b> Loops</a></li>
<li class="chapter" data-level="8.8" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#mapping-functions"><i class="fa fa-check"></i><b>8.8</b> Mapping Functions</a></li>
<li class="chapter" data-level="8.9" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#more-information"><i class="fa fa-check"></i><b>8.9</b> More Information</a></li>
<li class="chapter" data-level="8.10" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#exercises-4"><i class="fa fa-check"></i><b>8.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html"><i class="fa fa-check"></i><b>9</b> More Complicated Analyses</a><ul>
<li class="chapter" data-level="9.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#other-datasets"><i class="fa fa-check"></i><b>9.1</b> Other Datasets</a><ul>
<li class="chapter" data-level="9.1.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#importing-your-own-data"><i class="fa fa-check"></i><b>9.1.1</b> Importing Your Own Data</a></li>
<li class="chapter" data-level="9.1.2" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#exporting-data"><i class="fa fa-check"></i><b>9.1.2</b> Exporting Data</a></li>
<li class="chapter" data-level="9.1.3" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#data-exploration"><i class="fa fa-check"></i><b>9.1.3</b> Data Exploration</a></li>
<li class="chapter" data-level="9.1.4" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#modeling-winners"><i class="fa fa-check"></i><b>9.1.4</b> Modeling Winners</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#logistic-models-1"><i class="fa fa-check"></i><b>9.2</b> Logistic Models</a></li>
<li class="chapter" data-level="9.3" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#modelling-metrics"><i class="fa fa-check"></i><b>9.3</b> Modelling Metrics</a><ul>
<li class="chapter" data-level="9.3.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#pseudo-r2"><i class="fa fa-check"></i><b>9.3.1</b> Pseudo-R<sup>2</sup></a></li>
<li class="chapter" data-level="9.3.2" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#area-under-the-roc-curve-auc"><i class="fa fa-check"></i><b>9.3.2</b> Area Under the ROC Curve (AUC)</a></li>
<li class="chapter" data-level="9.3.3" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#model-comparisons"><i class="fa fa-check"></i><b>9.3.3</b> Model Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#more-complicated-analyses-1"><i class="fa fa-check"></i><b>9.4</b> More Complicated Analyses</a><ul>
<li class="chapter" data-level="9.4.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#model-selection"><i class="fa fa-check"></i><b>9.4.1</b> Model Selection</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#relational-data"><i class="fa fa-check"></i><b>9.5</b> Relational Data</a><ul>
<li class="chapter" data-level="9.5.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#inner-join"><i class="fa fa-check"></i><b>9.5.1</b> Inner Join</a></li>
<li class="chapter" data-level="9.5.2" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#left-join"><i class="fa fa-check"></i><b>9.5.2</b> Left Join</a></li>
<li class="chapter" data-level="9.5.3" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#right-join"><i class="fa fa-check"></i><b>9.5.3</b> Right Join</a></li>
<li class="chapter" data-level="9.5.4" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#full-join"><i class="fa fa-check"></i><b>9.5.4</b> Full Join</a></li>
<li class="chapter" data-level="9.5.5" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#semi-join"><i class="fa fa-check"></i><b>9.5.5</b> Semi Join</a></li>
<li class="chapter" data-level="9.5.6" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#anti-join"><i class="fa fa-check"></i><b>9.5.6</b> Anti Join</a></li>
<li class="chapter" data-level="9.5.7" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#specifying-key-columns"><i class="fa fa-check"></i><b>9.5.7</b> Specifying Key Columns</a></li>
<li class="chapter" data-level="9.5.8" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#merging-multiple-dataframes"><i class="fa fa-check"></i><b>9.5.8</b> Merging Multiple Dataframes</a></li>
<li class="chapter" data-level="9.5.9" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#binding-dataframes"><i class="fa fa-check"></i><b>9.5.9</b> Binding Dataframes</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#exercises-5"><i class="fa fa-check"></i><b>9.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="playing-nicely-with-others.html"><a href="playing-nicely-with-others.html"><i class="fa fa-check"></i><b>10</b> Playing Nicely With Others</a><ul>
<li class="chapter" data-level="10.1" data-path="playing-nicely-with-others.html"><a href="playing-nicely-with-others.html#r-markdown"><i class="fa fa-check"></i><b>10.1</b> R Markdown</a><ul>
<li class="chapter" data-level="10.1.1" data-path="playing-nicely-with-others.html"><a href="playing-nicely-with-others.html#kable"><i class="fa fa-check"></i><b>10.1.1</b> Kable</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="playing-nicely-with-others.html"><a href="playing-nicely-with-others.html#latex"><i class="fa fa-check"></i><b>10.2</b> LaTex</a></li>
<li class="chapter" data-level="10.3" data-path="playing-nicely-with-others.html"><a href="playing-nicely-with-others.html#github"><i class="fa fa-check"></i><b>10.3</b> Git(Hub)</a><ul>
<li class="chapter" data-level="10.3.1" data-path="playing-nicely-with-others.html"><a href="playing-nicely-with-others.html#my-first-repository"><i class="fa fa-check"></i><b>10.3.1</b> My First Repository</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="playing-nicely-with-others.html"><a href="playing-nicely-with-others.html#commenting-code"><i class="fa fa-check"></i><b>10.4</b> Commenting Code</a></li>
<li class="chapter" data-level="10.5" data-path="playing-nicely-with-others.html"><a href="playing-nicely-with-others.html#further-reading-1"><i class="fa fa-check"></i><b>10.5</b> Further Reading</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="working-with-text.html"><a href="working-with-text.html"><i class="fa fa-check"></i><b>11</b> Working with Text</a><ul>
<li class="chapter" data-level="11.1" data-path="working-with-text.html"><a href="working-with-text.html#working-with-stringr"><i class="fa fa-check"></i><b>11.1</b> Working with Stringr</a></li>
<li class="chapter" data-level="11.2" data-path="working-with-text.html"><a href="working-with-text.html#regular-expressions"><i class="fa fa-check"></i><b>11.2</b> Regular Expressions</a></li>
<li class="chapter" data-level="11.3" data-path="working-with-text.html"><a href="working-with-text.html#case-study"><i class="fa fa-check"></i><b>11.3</b> Case Study</a></li>
<li class="chapter" data-level="11.4" data-path="working-with-text.html"><a href="working-with-text.html#further-reading-2"><i class="fa fa-check"></i><b>11.4</b> Further Reading</a></li>
<li class="chapter" data-level="11.5" data-path="working-with-text.html"><a href="working-with-text.html#exercises-6"><i class="fa fa-check"></i><b>11.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="working-with-dates-and-times.html"><a href="working-with-dates-and-times.html"><i class="fa fa-check"></i><b>12</b> Working with Dates and Times</a><ul>
<li class="chapter" data-level="12.1" data-path="working-with-dates-and-times.html"><a href="working-with-dates-and-times.html#dates-in-r"><i class="fa fa-check"></i><b>12.1</b> Dates in R</a></li>
<li class="chapter" data-level="12.2" data-path="working-with-dates-and-times.html"><a href="working-with-dates-and-times.html#converting-to-dates"><i class="fa fa-check"></i><b>12.2</b> Converting To Dates</a></li>
<li class="chapter" data-level="12.3" data-path="working-with-dates-and-times.html"><a href="working-with-dates-and-times.html#extracting-from-dates"><i class="fa fa-check"></i><b>12.3</b> Extracting From Dates</a></li>
<li class="chapter" data-level="12.4" data-path="working-with-dates-and-times.html"><a href="working-with-dates-and-times.html#math-with-dates"><i class="fa fa-check"></i><b>12.4</b> Math with Dates</a></li>
<li class="chapter" data-level="12.5" data-path="working-with-dates-and-times.html"><a href="working-with-dates-and-times.html#time-zones"><i class="fa fa-check"></i><b>12.5</b> Time Zones</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="what-next.html"><a href="what-next.html"><i class="fa fa-check"></i><b>13</b> What Next</a><ul>
<li class="chapter" data-level="13.1" data-path="what-next.html"><a href="what-next.html#machine-learning-methods"><i class="fa fa-check"></i><b>13.1</b> Machine Learning Methods</a></li>
<li class="chapter" data-level="13.2" data-path="what-next.html"><a href="what-next.html#leaflet-maps"><i class="fa fa-check"></i><b>13.2</b> Leaflet Maps</a></li>
<li class="chapter" data-level="13.3" data-path="what-next.html"><a href="what-next.html#flexdashboard"><i class="fa fa-check"></i><b>13.3</b> FlexDashboard</a></li>
<li class="chapter" data-level="13.4" data-path="what-next.html"><a href="what-next.html#bookdown"><i class="fa fa-check"></i><b>13.4</b> Bookdown</a></li>
<li class="chapter" data-level="13.5" data-path="what-next.html"><a href="what-next.html#blogdown"><i class="fa fa-check"></i><b>13.5</b> Blogdown</a></li>
<li class="chapter" data-level="13.6" data-path="what-next.html"><a href="what-next.html#shiny"><i class="fa fa-check"></i><b>13.6</b> Shiny</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html"><i class="fa fa-check"></i><b>14</b> Basic Statistics (Using R)</a><ul>
<li class="chapter" data-level="14.1" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#purpose-of-the-unit"><i class="fa fa-check"></i><b>14.1</b> Purpose of the Unit</a></li>
<li class="chapter" data-level="14.2" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#definitions"><i class="fa fa-check"></i><b>14.2</b> Definitions</a><ul>
<li class="chapter" data-level="14.2.1" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#data-concepts"><i class="fa fa-check"></i><b>14.2.1</b> Data Concepts</a></li>
<li class="chapter" data-level="14.2.2" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#statistical-terms"><i class="fa fa-check"></i><b>14.2.2</b> Statistical Terms</a></li>
<li class="chapter" data-level="14.2.3" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#models-and-tests"><i class="fa fa-check"></i><b>14.2.3</b> Models and Tests</a></li>
<li class="chapter" data-level="14.2.4" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#how-well-compare-models"><i class="fa fa-check"></i><b>14.2.4</b> How We’ll Compare Models</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#exercises-7"><i class="fa fa-check"></i><b>14.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="other-resources.html"><a href="other-resources.html"><i class="fa fa-check"></i><b>15</b> Other Resources</a><ul>
<li class="chapter" data-level="" data-path="other-resources.html"><a href="other-resources.html#infographics"><i class="fa fa-check"></i>Infographics</a></li>
<li class="chapter" data-level="" data-path="other-resources.html"><a href="other-resources.html#courses"><i class="fa fa-check"></i>Courses</a></li>
<li class="chapter" data-level="" data-path="other-resources.html"><a href="other-resources.html#textbooks"><i class="fa fa-check"></i>Textbooks</a></li>
<li class="chapter" data-level="" data-path="other-resources.html"><a href="other-resources.html#blog-links"><i class="fa fa-check"></i>Blog Links</a></li>
<li class="chapter" data-level="" data-path="other-resources.html"><a href="other-resources.html#data-sources"><i class="fa fa-check"></i>Data Sources</a></li>
<li class="chapter" data-level="" data-path="other-resources.html"><a href="other-resources.html#graphing-aids"><i class="fa fa-check"></i>Graphing Aids</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="frequently-asked-questions.html"><a href="frequently-asked-questions.html"><i class="fa fa-check"></i><b>16</b> Frequently Asked Questions</a><ul>
<li class="chapter" data-level="16.1" data-path="frequently-asked-questions.html"><a href="frequently-asked-questions.html#why-r"><i class="fa fa-check"></i><b>16.1</b> Why R?</a></li>
<li class="chapter" data-level="16.2" data-path="frequently-asked-questions.html"><a href="frequently-asked-questions.html#why-is-my-code-broken"><i class="fa fa-check"></i><b>16.2</b> Why is my code broken?</a></li>
<li class="chapter" data-level="16.3" data-path="frequently-asked-questions.html"><a href="frequently-asked-questions.html#why-is-x-package-named-that"><i class="fa fa-check"></i><b>16.3</b> Why is (<em>X</em> package) named that?</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="changelog.html"><a href="changelog.html"><i class="fa fa-check"></i><b>17</b> Changelog</a><ul>
<li class="chapter" data-level="17.1" data-path="changelog.html"><a href="changelog.html#version-1.1.0"><i class="fa fa-check"></i><b>17.1</b> Version 1.1.0</a></li>
<li class="chapter" data-level="17.2" data-path="changelog.html"><a href="changelog.html#version-1.0.1"><i class="fa fa-check"></i><b>17.2</b> Version 1.0.1</a></li>
<li class="chapter" data-level="17.3" data-path="changelog.html"><a href="changelog.html#version-1.0.0"><i class="fa fa-check"></i><b>17.3</b> Version 1.0.0</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Data Exploration and Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modeling-data" class="section level1">
<h1><span class="header-section-number">6</span> Modeling Data</h1>
<blockquote>
“For such a model there is no need to ask the question “Is the model true?”. If “truth” is to be the “whole truth” the answer must be “No”. The only question of interest is “Is the model illuminating and useful?”
&lt;div align = “right” — George Box
</div>
</blockquote>
<div id="why-model" class="section level2">
<h2><span class="header-section-number">6.1</span> Why Model?</h2>
<p>We’ve now learned how to wrangle our data and begin exploring it in R, which are both crucial steps of the process. However, when people think about data analytics, they’re usually picturing a tool that will help them answer questions they have, providing information they can use to make decisions. The skills we’ve built so far will help you find questions in your data and begin exploring patterns, but this chapter will help you find answers.</p>
<p>And so comes the penultimate step in our data analysis framework, making a model. Models are summaries of relationships within our data, letting us see more clearly how changes in certain variables impact the others. We can then use that information to predict future outcomes, or to help us understand our dataset.</p>
<p>Now, we’ll be using our gapminder dataset throughout this chapter, which means there is one thing we can’t do with our models - we can’t use them to confirm a hypothesis. Hypothesis testing is much more prevalent in scientific fields than in business applications, and requires you to have started your analysis with a stated hypothesis and a plan of how you’ll test it. We didn’t do that - instead, we looked for how our variables interacted, and took the main pattern that we’ll be analyzing - how life expectancy interacts with GDP - straight from our exploratory analysis. As such, we can’t claim that our data <em>proves</em> anything, just that it shows our values are correlated.</p>
<p>Instead, our analysis is entirely <em>exploratory</em> - which isn’t a bad thing! Often times, exploratory analysis is necessary to justify further confirmatory studies. I’ve always liked a quote from Brian McGill on the matter:</p>
<blockquote>
If exploratory statistics weren’t treated like the crazy uncle nobody wants to talk about and everybody is embarrassed to admit being related to, science would be much better off.
<div align="right">
— <a href="https://dynamicecology.wordpress.com/2013/10/16/in-praise-of-exploratory-statistics/">Brian McGill</a>
</div>
</blockquote>
<p>But we’re getting off topic now. Suffice it to say that we’ll be building models that demonstrate how our variables are related, and using those models to generate predictions. The goal isn’t to teach you much about how these models work “under the hood” - for that, I’d suggest looking at other resources, perhaps starting with <a href="https://pdfs.semanticscholar.org/7a07/5776db74495a03ca38750513f331b80f687e.pdf">this paper</a>. Instead, we’ll go over how to build and use these models in R, with more of an emphasis on “how” than “why”.</p>
</div>
<div id="linear-models" class="section level2">
<h2><span class="header-section-number">6.2</span> Linear Models</h2>
<p>Our first and simplest model is the linear model. Thinking back to last chapter, we made a graph that showed the relationship between GDP and life expectancy:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(gapminder)
<span class="kw">library</span>(tidyverse)</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;ggplot2&#39;:
##   method         from 
##   [.quosures     rlang
##   c.quosures     rlang
##   print.quosures rlang</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;rvest&#39;:
##   method            from
##   read_xml.response xml2</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.1.1       ✔ purrr   0.3.2  
## ✔ tibble  2.1.1       ✔ dplyr   0.8.0.1
## ✔ tidyr   0.8.3       ✔ stringr 1.4.0  
## ✔ readr   1.3.1       ✔ forcats 0.4.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(gapminder_unfiltered, <span class="kw">aes</span>(gdpPercap, lifeExp)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre>
<p><img src="06_Modeling_Your_Data_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>A linear model tries to summarize this relationship in a single straight line (sometimes known as a <em>line of best fit</em>), which in this case would look something like the following:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(gapminder_unfiltered, <span class="kw">aes</span>(gdpPercap, lifeExp)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</code></pre>
<p><img src="06_Modeling_Your_Data_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>(You might remember <code>geom_smooth()</code> from chapter 2 - it adds a trendline to our graph. By specifying <code>method = &quot;lm&quot;</code>, we told it to graph the line we’d get from a <em>linear model</em>.)</p>
<p>This model claims that for every possible GDP level present in our dataset, there’s a set life expectancy. Those values are the ones traced by the line - so countries with a GDP of 0 should expect life expectancies around 60, for instance.</p>
<p>This is a good moment to revisit the quote that opened this chapter, from legendary statistician George Box. His full quote has gotten a bit mangled over the years, to the point that most people know it more simply as:</p>
<blockquote>
<p>All models are wrong; some models are useful.</p>
</blockquote>
<p>For instance, it’s obvious that our linear model here is wrong for the great majority of countries - the richest countries in our dataset ought to be living well into their 130s, according to the line. However, it is useful to an extent - it shows us that our variables are positively correlated, and gives us an idea of how to move forward. It is not so useful, however, that we should spend too much time picking values out from along the line.</p>
<p>Of course, it would be much easier for us to just calculate the number from a formula, rather than finding the point on the graph! To see the actual model formula, we can use the <code>lm()</code> function. This function creates a linear model and requires two main arguments:</p>
<ul>
<li>A formula, of the format Y ~ X (Where Y is your response variable, X your predictor variables, and you read the “~” as “as a function of”)</li>
<li>A dataset</li>
</ul>
<p>The usage looks like this:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm</span>(lifeExp <span class="op">~</span><span class="st"> </span>gdpPercap, <span class="dt">data =</span> gapminder_unfiltered)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ gdpPercap, data = gapminder_unfiltered)
## 
## Coefficients:
## (Intercept)    gdpPercap  
##   5.782e+01    6.562e-04</code></pre>
<p>So what we can tell here is that for every 1 increase in GDP, we can expect to see a 0.0006562 year increase in life expectancy. That’s not particularly large - but then, a single dollar increase of GDP isn’t very much, either! To understand our model better, we can call the <code>summary()</code> function on the model:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(lifeExp <span class="op">~</span><span class="st"> </span>gdpPercap, <span class="dt">data =</span> gapminder_unfiltered))</code></pre>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ gdpPercap, data = gapminder_unfiltered)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -74.282  -3.902   3.282   6.161  16.003 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 5.782e+01  2.232e-01  258.97   &lt;2e-16 ***
## gdpPercap   6.563e-04  1.392e-05   47.14   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.108 on 3311 degrees of freedom
## Multiple R-squared:  0.4017, Adjusted R-squared:  0.4015 
## F-statistic:  2223 on 1 and 3311 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Here we get a little more information on how well our model fits the data. We can see p-values for our overall model and for each variable (check out Chapter 14 for more information on these), as well as our model R<sup>2</sup>. The R<sup>2</sup> value represents how much of the variance in your dataset can be explained by your model - basically, how good a fit your model is to the data. Generally, we use the adjusted R<sup>2</sup>, which compensates for how many variables you’re using in your model - otherwise, adding another variable <em>always</em> increases your multiple R<sup>2</sup>.</p>
<p>But you might recall that we saw a much more normal linear relationship between our variables when we log-transformed GDP:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(gapminder_unfiltered, <span class="kw">aes</span>(<span class="kw">log</span>(gdpPercap), lifeExp)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</code></pre>
<p><img src="06_Modeling_Your_Data_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>So that would make me guess that our model would also be improved by log-transforming the GDP term in our model - just look at how much better that line fits on the second graph. Let’s try it now:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(lifeExp <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(gdpPercap), <span class="dt">data =</span> gapminder_unfiltered))</code></pre>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ log(gdpPercap), data = gapminder_unfiltered)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -32.622  -2.154   0.826   3.380  17.884 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    -4.87455    0.77505  -6.289 3.61e-10 ***
## log(gdpPercap)  8.02711    0.08785  91.374  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.274 on 3311 degrees of freedom
## Multiple R-squared:  0.716,  Adjusted R-squared:  0.716 
## F-statistic:  8349 on 1 and 3311 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Note that I didn’t print out the model statement this time - <code>summary()</code> provides us all the information <code>lm()</code> does, so we can just call it instead.</p>
<p>We can see that our R<sup>2</sup> value shot up - we’re now at 0.716, instead of 0.402! So log-transforming our data seems to help our model fit the data better.</p>
<p>We also, last chapter, realized that the continent a country was on and the year of an observation were probably relevant to the analysis. We can add those to our model using <code>+</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(lifeExp <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(gdpPercap) <span class="op">+</span><span class="st"> </span>continent <span class="op">+</span><span class="st"> </span>year, <span class="dt">data =</span> gapminder_unfiltered))</code></pre>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ log(gdpPercap) + continent + year, data = gapminder_unfiltered)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -24.3094  -2.2425   0.2411   2.7085  15.4838 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -3.144e+02  1.085e+01  -28.97   &lt;2e-16 ***
## log(gdpPercap)     5.015e+00  1.040e-01   48.21   &lt;2e-16 ***
## continentAmericas  9.459e+00  3.521e-01   26.86   &lt;2e-16 ***
## continentAsia      8.084e+00  3.078e-01   26.26   &lt;2e-16 ***
## continentEurope    1.227e+01  3.393e-01   36.15   &lt;2e-16 ***
## continentFSU       9.903e+00  4.943e-01   20.04   &lt;2e-16 ***
## continentOceania   1.040e+01  4.645e-01   22.39   &lt;2e-16 ***
## year               1.653e-01  5.611e-03   29.46   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.029 on 3305 degrees of freedom
## Multiple R-squared:  0.8179, Adjusted R-squared:  0.8175 
## F-statistic:  2120 on 7 and 3305 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This also got our R<sup>2</sup> up, all the way to 0.818! However, you might notice that our summary output is getting much longer - we now have a row for each of the continents in our dataset (minus Africa, for reasons that are outside of this text - the short explanation is that Africa is what all other continents are being compared to; so being in Europe gives you, on average, 12.27 more years of life than being in Africa, for instance). If we wanted a bit more legible output, we could instead use an ANOVA test - which deals with categorical variables (like continent) as a single unit, rather than as each of the possible levels:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(<span class="kw">aov</span>(lifeExp <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(gdpPercap) <span class="op">+</span><span class="st"> </span>continent <span class="op">+</span><span class="st"> </span>year, <span class="dt">data =</span> gapminder_unfiltered))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: lifeExp
##                  Df Sum Sq Mean Sq  F value    Pr(&gt;F)    
## log(gdpPercap)    1 328670  328670 12994.28 &lt; 2.2e-16 ***
## continent         5  24795    4959   196.06 &lt; 2.2e-16 ***
## year              1  21950   21950   867.82 &lt; 2.2e-16 ***
## Residuals      3305  83595      25                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>However, ANOVA isn’t particularly useful for most purposes, as it just reports <em>if</em> a variable has an impact on your response, rather than <em>how</em> it does so (more on that <a href="https://dynamicecology.wordpress.com/2012/11/27/ecologists-need-to-do-a-better-job-of-prediction-part-i-the-insidious-evils-of-anova/">here</a> or <a href="https://dynamicecology.wordpress.com/2014/10/02/interpreting-anova-interactions-and-model-selection/">here</a>), so we won’t go into depth with it. Suffice it to say that ANOVA is a special type of linear regression, sometimes used in science, that isn’t particularly useful for most other applications.</p>
<p>Anyway. The last thing I want to mention is that the model assumes each predictor variable is independent from each other, and they don’t vary with one another. However, we can be pretty sure that isn’t true for GDP and continent - we can generally assume that most countries in Oceania have a higher GDP per capita than most countries in Africa, for instance. As such, we should include an <em>interaction</em> term between those two variables - which we can do by replacing the <code>+</code> between those terms in our model statement with <code>*</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(lifeExp <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(gdpPercap) <span class="op">*</span><span class="st"> </span>continent <span class="op">+</span><span class="st"> </span>year, <span class="dt">data =</span> gapminder_unfiltered))</code></pre>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ log(gdpPercap) * continent + year, data = gapminder_unfiltered)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -24.4999  -2.1933   0.4236   2.3497  15.3682 
## 
## Coefficients:
##                                    Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                      -3.441e+02  1.124e+01 -30.604  &lt; 2e-16
## log(gdpPercap)                    5.013e+00  2.285e-01  21.942  &lt; 2e-16
## continentAmericas                -4.510e+00  2.922e+00  -1.543   0.1228
## continentAsia                     5.749e+00  2.065e+00   2.784   0.0054
## continentEurope                   3.166e+01  2.663e+00  11.887  &lt; 2e-16
## continentFSU                      5.070e+01  7.517e+00   6.745 1.80e-11
## continentOceania                 -1.465e+00  3.941e+00  -0.372   0.7100
## year                              1.803e-01  5.694e-03  31.661  &lt; 2e-16
## log(gdpPercap):continentAmericas  1.563e+00  3.514e-01   4.447 8.99e-06
## log(gdpPercap):continentAsia      2.812e-01  2.705e-01   1.040   0.2985
## log(gdpPercap):continentEurope   -2.037e+00  3.142e-01  -6.481 1.05e-10
## log(gdpPercap):continentFSU      -4.663e+00  8.633e-01  -5.402 7.07e-08
## log(gdpPercap):continentOceania   1.283e+00  4.477e-01   2.865   0.0042
##                                     
## (Intercept)                      ***
## log(gdpPercap)                   ***
## continentAmericas                   
## continentAsia                    ** 
## continentEurope                  ***
## continentFSU                     ***
## continentOceania                    
## year                             ***
## log(gdpPercap):continentAmericas ***
## log(gdpPercap):continentAsia        
## log(gdpPercap):continentEurope   ***
## log(gdpPercap):continentFSU      ***
## log(gdpPercap):continentOceania  ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.908 on 3300 degrees of freedom
## Multiple R-squared:  0.8268, Adjusted R-squared:  0.8262 
## F-statistic:  1313 on 12 and 3300 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>And as we can see, our adjusted R<sup>2</sup> has gone up even further, to 0.826!</p>
<p>Note, by the way, that you can also add interaction terms very explicitly to your model by adding the interaction term (written as <code>Term1:Term2</code>) to the formula with <code>+</code>. In our case, that would look like this:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(lifeExp <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(gdpPercap) <span class="op">+</span><span class="st"> </span>continent <span class="op">+</span><span class="st"> </span>year <span class="op">+</span><span class="st"> </span>(<span class="kw">log</span>(gdpPercap))<span class="op">:</span>continent, <span class="dt">data =</span> gapminder_unfiltered))</code></pre>
<p>That line of code would give us the same output as using <code>*</code> above.</p>
</div>
<div id="model-predictions" class="section level2">
<h2><span class="header-section-number">6.3</span> Model Predictions</h2>
<p>We can now use our model to generate predictions! To do so, we first want to assign our model to an object, to make our code a little easier to understand:</p>
<pre class="sourceCode r"><code class="sourceCode r">gapMod &lt;-<span class="st"> </span><span class="kw">lm</span>(lifeExp <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(gdpPercap) <span class="op">+</span><span class="st"> </span>continent <span class="op">+</span><span class="st"> </span>year <span class="op">+</span><span class="st"> </span>(<span class="kw">log</span>(gdpPercap))<span class="op">:</span>continent, <span class="dt">data =</span> gapminder_unfiltered)</code></pre>
<p>We’ll now clone our dataset into a new dataframe, which is also where we’re going to store predictions. We could skip this step and just add the columns to the gapminder dataset, but I don’t like changing our base dataframe, just in case something goes wrong - I usually prefer to edit copied dataframes.</p>
<pre class="sourceCode r"><code class="sourceCode r">gapPred &lt;-<span class="st"> </span>gapminder_unfiltered</code></pre>
<p>We’re now ready to make our predictions, which we’ll store in a column called “predict”. We can use the <code>predict()</code> function to do this, which (with linear models) requires two arguements: first, what model you’re using to make your predictions, and second, what data you’re using to make these predictions. The code to do this looks something like this:</p>
<pre class="sourceCode r"><code class="sourceCode r">gapPred &lt;-<span class="st"> </span>gapPred <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">predict =</span> <span class="kw">predict</span>(gapMod, <span class="dt">newdata =</span> gapPred))</code></pre>
<p>(This, by the way, is also how you’d use your models to generate forecasts, when you don’t actually know the true value you’re predicting. We’re working with complete datasets in this unit to demonstrate how to assess the results of your predictions, but there’s no real difference between this application and the forecasting techniques professionals use these sorts of models for.)</p>
<p>We can preview our predictions by peaking at the dataframe - remember, we’re comparing the <code>lifeExp</code> and <code>predict</code> columns:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(gapPred)</code></pre>
<pre><code>## # A tibble: 6 x 7
##   country     continent  year lifeExp      pop gdpPercap predict
##   &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 Afghanistan Asia       1952    28.8  8425333      779.    48.8
## 2 Afghanistan Asia       1957    30.3  9240934      821.    50.0
## 3 Afghanistan Asia       1962    32.0 10267083      853.    51.1
## 4 Afghanistan Asia       1967    34.0 11537966      836.    51.9
## 5 Afghanistan Asia       1972    36.1 13079460      740.    52.1
## 6 Afghanistan Asia       1977    38.4 14880372      786.    53.3</code></pre>
<p>That doesn’t give me a ton of confidence - but remember, we’re only looking at 6 out of more than 3,300 predictions! We could attempt plotting the predictions over the real values:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(gapPred, <span class="kw">aes</span>(gdpPercap)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> lifeExp)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> predict), <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.25</span>)</code></pre>
<p><img src="06_Modeling_Your_Data_files/figure-html/unnamed-chunk-15-1.png" width="672" />
(Remember, <code>alpha = 0.25</code> made the blue points 75% transparent - or, well, 25% opaque.)</p>
<p>But while I can tell that our predictions seem to generally fit the right pattern, I have no way of telling how well any individual prediction performed - it’s possible all our highest points represent the lowest values, for instance. A better way is to calculate the <em>residuals</em> for your model by subtracting the real values (our life expectancy) from the predictions. This number shows how good any given prediction is, and is actually what R<sup>2</sup> is based on - a higher R<sup>2</sup> means a model has generally lower residuals. We’ll then plot those residuals against our predictions, to see how well we did:</p>
<pre class="sourceCode r"><code class="sourceCode r">gapPred <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">resid =</span> predict<span class="op">-</span>lifeExp) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(predict, resid)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;segment&quot;</span>, <span class="dt">x =</span> <span class="op">-</span><span class="ot">Inf</span>, <span class="dt">xend =</span> <span class="ot">Inf</span>, <span class="dt">y =</span> <span class="dv">0</span>, <span class="dt">yend =</span> <span class="dv">0</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)</code></pre>
<p><img src="06_Modeling_Your_Data_files/figure-html/unnamed-chunk-16-1.png" width="672" />
(See what I did there, by using <code>ggplot()</code> with the pipe? Note that you still have to use <code>+</code> to add things to your plots.)</p>
<p>So it looks like our model does an <em>okay</em> job predicting life expectancy - most of the predictions are within five years, though some are pretty dramatically off. The plot also exhibits heteroscedasticity and nonlinearity, neither of which I’m going to get into here - check out <a href="http://docs.statwing.com/interpreting-residual-plots-to-improve-your-regression/">this post</a> for more information. The short version is that we could certainly improve our model, by getting into a little more advanced statistics - but the model we’ve built does an okay job, and could probably be used to generate predictions.</p>
<p>(By the way, you can get a very quick version of this plot - alongside a few other useful model plots - using <code>plot(YourModel)</code> - so in this case, <code>plot(gapMod)</code>).</p>
</div>
<div id="classification" class="section level2">
<h2><span class="header-section-number">6.4</span> Classification</h2>
<p>These linear models we’ve been building have been good for predicting numeric values - the number of years a person might live, or (in other situations) how many customers will click a link or how many frogs will be in a pond. That’s because we’ve been building <em>regression</em> models, which are useful for these sorts of tasks. However, we often want to predict events or categories, not just a numeric value - we want to know what species a flower might be, whether or not someone will click a link we email them, or if a tree will die this year.</p>
<p>For these tasks, we need to use a <em>classification</em> model. To walk through how these work, let’s start using a new dataset included in base R - <code>mtcars</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(mtcars)</code></pre>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<p>To understand what each of these column abbreviations mean, try typing <code>?mtcars</code> into the console. What we want to do is predict if cars have either automatic or manual transmissions, which is coded in the <code>am</code> column - 0 means a car is an automatic, while 1 represents a manual - based on the MPG and horsepower of the car. If we went through the same steps as we did for the linear model, we’d then go ahead and make a quick graph to see how well a linear model fits our data:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(mpg, am)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> F)</code></pre>
<p><img src="06_Modeling_Your_Data_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Judging based on our past models, this doesn’t look great! Our model isn’t particularly close to any points.</p>
<p>That’s a natural occurance when trying to classify data, however. Our model isn’t actually showing us what value a point has - instead, it’s showing us the <em>probability</em> that a data point belongs to the 1 group (in this example, if a car has a manual transmission). You can then decide how certain you want to be before assigning the data point to that 1 group - usually, if the model gives a 50% or more probability to being a 1, we assign it to that group. We can visualize what the results of this process would look like for our dataset with our very simple model only using MPG - the red triangles are misclassified, while the green circles were accurately guessed by the model:
<img src="06_Modeling_Your_Data_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>So our model got it about 78% right - not bad, for a single variable model! This is a fully acceptable use of a linear model for classification - it’s simple and mostly does the job. If you’ve ever worked with economics research, you’ve probably seen linear models used this way before.</p>
</div>
<div id="logistic-models" class="section level2">
<h2><span class="header-section-number">6.5</span> Logistic Models</h2>
<p>However, there are a few statistics-based reasons that we don’t want to use that simple straight line for classification problems. If your data has heavy tails - that is, if there are points that are going to have something like 5% or 95% chances of belonging in the 1 group, the linear formula begins to break down somewhat. It also performs badly when your predictors are, well, non-linear - that is, when both high and low values of a predictor make being a 0 more likely, with middle values tending to be 1s.</p>
<p>Instead, we want to use a logistic model, which will give us a line that looks more like this:</p>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="06_Modeling_Your_Data_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>That curvy line works exactly the same way our linear model did - points with higher than 50% probability of being “1”s are assigned a 1, and so on. And you can see that it classified our data slightly better, hitting 81% accuracy with exactly the same model formula as the linear had.</p>
<p>Not everyone is in agreement here - for instance, <a href="https://statisticalhorizons.com/linear-vs-logistic">here</a> is a professor arguing that the simplicity of linear models make them the best choice for the majority of data sets. However, I think the two models are in practice as easy to implement and understand, and the logistic model is usually a better classifier. As such, I usually rely on logistic models to classify my datasets.</p>
<p>Making these models is a pretty similar process to making linear models. We’ll use the <code>glm()</code> function, rather than <code>lm()</code>, as the logistic model is one of the family of algorithms known as a <em>generalized linear model</em>. We’ll still need to supply the formula and data arguments, just like with <code>lm()</code>. The main difference with <code>glm()</code> is that we also need to specify the argument <code>family</code>. In this case, we want to specify that <code>family = binomial</code>, which will calculate the logistic model for us.</p>
<p>With all that in mind, we can build our model with the following line of code:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glm</span>(am <span class="op">~</span><span class="st"> </span>mpg, <span class="dt">data =</span> mtcars, <span class="dt">family =</span> binomial)</code></pre>
<pre><code>## 
## Call:  glm(formula = am ~ mpg, family = binomial, data = mtcars)
## 
## Coefficients:
## (Intercept)          mpg  
##      -6.604        0.307  
## 
## Degrees of Freedom: 31 Total (i.e. Null);  30 Residual
## Null Deviance:       43.23 
## Residual Deviance: 29.68     AIC: 33.68</code></pre>
<p>And we can see the model summary just like we did with <code>lm()</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r">logmod &lt;-<span class="st"> </span><span class="kw">glm</span>(am <span class="op">~</span><span class="st"> </span>mpg, <span class="dt">data =</span> mtcars, <span class="dt">family =</span> binomial)
<span class="kw">summary</span>(logmod)</code></pre>
<pre><code>## 
## Call:
## glm(formula = am ~ mpg, family = binomial, data = mtcars)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5701  -0.7531  -0.4245   0.5866   2.0617  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)  -6.6035     2.3514  -2.808  0.00498 **
## mpg           0.3070     0.1148   2.673  0.00751 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 43.230  on 31  degrees of freedom
## Residual deviance: 29.675  on 30  degrees of freedom
## AIC: 33.675
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>(Go ahead and save the model in <code>logmod</code>, like I just did - we’ll use that in a second).</p>
<p>We could go ahead and drill down our model even further, adding other variables and changing the formula just like we did with linear models earlier:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">glm</span>(am <span class="op">~</span><span class="st"> </span>hp <span class="op">+</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars, <span class="dt">family=</span><span class="st">&quot;binomial&quot;</span>))</code></pre>
<pre><code>## 
## Call:
## glm(formula = am ~ hp + wt, family = &quot;binomial&quot;, data = mtcars)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2537  -0.1568  -0.0168   0.1543   1.3449  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept) 18.86630    7.44356   2.535  0.01126 * 
## hp           0.03626    0.01773   2.044  0.04091 * 
## wt          -8.08348    3.06868  -2.634  0.00843 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 43.230  on 31  degrees of freedom
## Residual deviance: 10.059  on 29  degrees of freedom
## AIC: 16.059
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<p>In fact, logistic models made with the <code>glm()</code> function work pretty much the same as linear models made with <code>lm()</code>. There are only two big differences that I want to highlight, as far as use cases are concerned.</p>
<p>The first of these is when using the model to make predictions. For instance, let’s take that model I just made above and assign it to <code>mtmod</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r">mtmod &lt;-<span class="st"> </span><span class="kw">glm</span>(am <span class="op">~</span><span class="st"> </span>hp <span class="op">+</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars, <span class="dt">family=</span><span class="st">&quot;binomial&quot;</span>)</code></pre>
<p>Remember earlier, how we could generate predictions from our models using <code>predict(model, data)</code>? Let’s look at what happens if we did something similar here:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">predict</span>(mtmod, mtcars))</code></pre>
<pre><code>##         Mazda RX4     Mazda RX4 Wag        Datsun 710    Hornet 4 Drive 
##         1.6757093        -0.3855769         3.4844067        -3.1339584 
## Hornet Sportabout           Valiant 
##        -2.5961266        -5.2956878</code></pre>
<p>That doesn’t look right at all! By this interpretation, the Valiant has a -530% chance of having a manual transmission - a number which shouldn’t be possible, as probabilities don’t go below 0.</p>
<p>The explanation for why this happens, but it boils down to R trying to use our model to make predictions like it’s a linear model, not a logistic one. To fix this, we just have to specify <code>type = &quot;response&quot;</code> in our <code>predict()</code> call:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">predict</span>(mtmod, mtcars, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>))</code></pre>
<pre><code>##         Mazda RX4     Mazda RX4 Wag        Datsun 710    Hornet 4 Drive 
##       0.842335537       0.404782533       0.970240822       0.041728035 
## Hornet Sportabout           Valiant 
##       0.069388122       0.004988159</code></pre>
<p>And voila, we generate probabilities.</p>
</div>
<div id="evaluating-and-comparing-models" class="section level2">
<h2><span class="header-section-number">6.6</span> Evaluating and Comparing Models</h2>
<p>The second thing you might have noticed in our logistic models section is that I didn’t mention R<sup>2</sup> even once. That’s because R<sup>2</sup> doesn’t really work for logistic models - we don’t really have a good equivalent of a “residual” to use to calculate it from.</p>
<p>If we’re deadset on comparing our models using R<sup>2</sup>, we can choose from one of several pseudo-R<sup>2</sup> provided by the <code>pR2</code> function from the <code>pscl</code> package:</p>
<pre><code>install.packages(&quot;pscl&quot;)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">pscl<span class="op">::</span><span class="kw">pR2</span>(mtmod)</code></pre>
<pre><code>##         llh     llhNull          G2    McFadden        r2ML        r2CU 
##  -5.0295552 -21.6148666  33.1706228   0.7673104   0.6453351   0.8708970</code></pre>
<p>If you’re going to do this, I reccomend using the McFadden R<sup>2</sup>, or the r<sup>2</sup>CU (which stands for Cragg and Uhler, by the way). However, whichever pseudo-R<sup>2</sup> you use, make sure you stay consistent - the different pseudo-R<sup>2</sup> cannot be compared to one another. None of these can be compared to the R<sup>2</sup> you’ll get off a linear model, either - they’re a completely different metric.</p>
<p>These pseudo-R<sup>2</sup> aren’t quite the most common method used to compare models, however. Much more commonly used is the Akaike Information Criterion, also called AIC. You may have noticed that AIC prints at the bottom of the <code>summary()</code> printouts for logistic models:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(logmod)</code></pre>
<pre><code>## 
## Call:
## glm(formula = am ~ mpg, family = binomial, data = mtcars)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5701  -0.7531  -0.4245   0.5866   2.0617  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)  -6.6035     2.3514  -2.808  0.00498 **
## mpg           0.3070     0.1148   2.673  0.00751 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 43.230  on 31  degrees of freedom
## Residual deviance: 29.675  on 30  degrees of freedom
## AIC: 33.675
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>And if we want, we can get just the AIC by selecting it with <code>$</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(mtmod)<span class="op">$</span>aic</code></pre>
<pre><code>## [1] 16.05911</code></pre>
<p>It’s important to understand what exactly AIC can be used for, as it’s frequently misapplied in both academia and industry. AIC can be used effectively in three ways:</p>
<ul>
<li><strong>Model selection</strong>, where you compare <em>every combination of scientifically justifiable variables possible</em> OR</li>
<li><strong>Variable analysis</strong> where you either compare your response variable against each predictor variable <em>independently</em> OR</li>
<li><strong>Variable analysis</strong> where you standardize your predictor variables, put them into a model, and compare their coefficients</li>
</ul>
<p>For all of these, AIC can only be used to compare models of the same type (so logistic to logistic is fine, logistic to linear isn’t), created on the same datasets, created using the same function. Otherwise, your comparisons will be meaningless and misleading - not adjectives you want associated with your work!</p>
<p>When comparing models, keep in mind that AIC is an (almost) arbitrary number that gets larger as your dataset gets larger - what’s important is not how large an AIC is overall, but how much larger (or smaller) it is than the AIC of your other models. That difference in AIC values is also known as <span class="math inline">\(\Delta\)</span>AIC. Your best model is going to be the one with the lowest AIC value - to compare models, subtract the smaller AIC value from the larger and then reference the chart below:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(knitr)
<span class="kw">library</span>(kableExtra)</code></pre>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tibble</span>(<span class="st">&quot;If the difference in AIC is:&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;0-2&quot;</span>, <span class="st">&quot;2-4&quot;</span>, <span class="st">&quot;4+&quot;</span>),
       <span class="st">&quot;The model with lowest AIC is:&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Identical to the other one&quot;</span>, <span class="st">&quot;Maybe better&quot;</span>, <span class="st">&quot;Definitely better&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">kable</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">kable_styling</span>(<span class="st">&quot;striped&quot;</span>)</code></pre>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
If the difference in AIC is:
</th>
<th style="text-align:left;">
The model with lowest AIC is:
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0-2
</td>
<td style="text-align:left;">
Identical to the other one
</td>
</tr>
<tr>
<td style="text-align:left;">
2-4
</td>
<td style="text-align:left;">
Maybe better
</td>
</tr>
<tr>
<td style="text-align:left;">
4+
</td>
<td style="text-align:left;">
Definitely better
</td>
</tr>
</tbody>
</table>
<p>For our example here, we can just quickly subtract the AIC values for both of our models:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(logmod)<span class="op">$</span>aic <span class="op">-</span><span class="st"> </span><span class="kw">summary</span>(mtmod)<span class="op">$</span>aic</code></pre>
<pre><code>## [1] 17.61606</code></pre>
<p>As the <span class="math inline">\(\Delta\)</span>AIC between these models is 17.6, we can very confidently say that our <code>mtmod</code> object is the better of these two models.</p>
<div id="confusion-matrices" class="section level3">
<h3><span class="header-section-number">6.6.1</span> Confusion Matrices</h3>
<p>However, as I mentioned earlier, AIC can’t really be used to compare models created by different functions. That can be a challenge when we want to compare, for instance, a linear and logistic classifier. Luckily enough, there are other ways we can go about solving this issue.</p>
<p>Let’s go ahead and create a linear version of our <code>mtmod</code> function, to start off with:</p>
<pre class="sourceCode r"><code class="sourceCode r">linmod &lt;-<span class="st"> </span><span class="kw">lm</span>(am <span class="op">~</span><span class="st"> </span>hp <span class="op">+</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars)</code></pre>
<p>We’ll now make a clone of <code>mtcars</code> called <code>mtcarspred</code>, and create two columns for our predictions - <code>lin</code> for the linear model, and <code>log</code> for the logistic. Note that for both of these I’m wrapping the <code>predict()</code> function in <code>round(, 0)</code> - this will automatically change the probabilities we’re getting from <code>predict()</code> into our 0/1 classification system.</p>
<pre class="sourceCode r"><code class="sourceCode r">mtcarspred &lt;-<span class="st"> </span>mtcars
mtcarspred<span class="op">$</span>lin &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">predict</span>(linmod, mtcarspred), <span class="dv">0</span>)
mtcarspred<span class="op">$</span>log &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">predict</span>(mtmod, mtcarspred, <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>), <span class="dv">0</span>)</code></pre>
<p>We’re now going to make what’s known as a <em>confusion matrix</em> for each of these predictions. This matrix will show us exactly how our model predictions differ from one another, and let us get a good sense of how accurate each model is. To make it, first we have to install the <code>caret</code> package:</p>
<pre><code>install.packages(&quot;caret&quot;)</code></pre>
<p>And now we can use the <code>confusionMatrix()</code> function to create our matrices. To do this, we pass the function factored versions of our prediction and true value columns - in that order, or else we’ll mess up a few of the calculations.</p>
<pre class="sourceCode r"><code class="sourceCode r">caret<span class="op">::</span><span class="kw">confusionMatrix</span>(<span class="kw">factor</span>(mtcarspred<span class="op">$</span>lin), <span class="kw">factor</span>(mtcarspred<span class="op">$</span>am))</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction  0  1
##          0 17  1
##          1  2 12
##                                           
##                Accuracy : 0.9062          
##                  95% CI : (0.7498, 0.9802)
##     No Information Rate : 0.5938          
##     P-Value [Acc &gt; NIR] : 0.000105        
##                                           
##                   Kappa : 0.808           
##                                           
##  Mcnemar&#39;s Test P-Value : 1.000000        
##                                           
##             Sensitivity : 0.8947          
##             Specificity : 0.9231          
##          Pos Pred Value : 0.9444          
##          Neg Pred Value : 0.8571          
##              Prevalence : 0.5938          
##          Detection Rate : 0.5312          
##    Detection Prevalence : 0.5625          
##       Balanced Accuracy : 0.9089          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<pre class="sourceCode r"><code class="sourceCode r">caret<span class="op">::</span><span class="kw">confusionMatrix</span>(<span class="kw">factor</span>(mtcarspred<span class="op">$</span>log), <span class="kw">factor</span>(mtcarspred<span class="op">$</span>am))</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction  0  1
##          0 18  1
##          1  1 12
##                                           
##                Accuracy : 0.9375          
##                  95% CI : (0.7919, 0.9923)
##     No Information Rate : 0.5938          
##     P-Value [Acc &gt; NIR] : 1.452e-05       
##                                           
##                   Kappa : 0.8704          
##                                           
##  Mcnemar&#39;s Test P-Value : 1               
##                                           
##             Sensitivity : 0.9474          
##             Specificity : 0.9231          
##          Pos Pred Value : 0.9474          
##          Neg Pred Value : 0.9231          
##              Prevalence : 0.5938          
##          Detection Rate : 0.5625          
##    Detection Prevalence : 0.5938          
##       Balanced Accuracy : 0.9352          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<p>As we can see, that function gives us a lot to work with. One of the most interesting to us is the matrix up top, which compares your predicted values to the actual ones. This, in combination with the Accuracy metric right below it, give us a sense for how our model performs, and exactly what it messes up on. There may be cases where you choose your model based more on this matrix than the actual accuracy - for instance, if a healthcare diagnostic model is slightly less accurate but generates fewer false negatives, erring on the side of caution might actually help save people’s lives.</p>
<p>For our example, however, it’s enough to just look at the accuracy metric. And once again, our logistic model outperforms the linear formula - a result that becomes even more common once you’re working with larger and larger datasets.</p>
</div>
</div>
<div id="conclusion" class="section level2">
<h2><span class="header-section-number">6.7</span> Conclusion</h2>
<p>We’ve now covered the two most common forms of models, and seen applications of modeling for both regression and classification. We’ve gone over how to select your best model, and how to use that best model to predict both values already in your dataset and values you don’t know yet. But even still, we’ve barely even scratched the surface of modeling - this is the sort of thing people get very expensive degrees in. Hopefully this chapter has helped you learn a bit more about models, and how to make them in R. Our next chapter returns to working with ggplot2 and similar packages, in order to help you share all your hard work - after all, what’s the point of an analysis no one else sees?</p>
</div>
<div id="exercises-3" class="section level2">
<h2><span class="header-section-number">6.8</span> Exercises</h2>
<ol style="list-style-type: decimal">
<li>What is the difference between regression and classification? What model types are better suited for each?</li>
<li>Find the best model formula for predicting <code>am</code> in the <code>mtcars</code> dataset. Use AIC to compare models, and feel free to transform the data.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-data-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="achieving-graphical-excellence.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
