<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Data Exploration and Analysis with R</title>
  <meta name="description" content="This is a course reader for a class that will never be taught. Hopefully it helps you nonetheless.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Data Exploration and Analysis with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a course reader for a class that will never be taught. Hopefully it helps you nonetheless." />
  <meta name="github-repo" content="MikeMahoney218/Intro_to_R_Reader" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Data Exploration and Analysis with R" />
  
  <meta name="twitter:description" content="This is a course reader for a class that will never be taught. Hopefully it helps you nonetheless." />
  

<meta name="author" content="Michael Mahoney">


<meta name="date" content="2018-11-01">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="functions-and-scripting.html">
<link rel="next" href="achieving-graphical-excellence.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to IDEAR</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html"><i class="fa fa-check"></i><b>1</b> Introduction to R and Data Visualization</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#lecture-notes"><i class="fa fa-check"></i><b>1.1</b> Lecture Notes</a><ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#what-is-r"><i class="fa fa-check"></i><b>1.1.1</b> What is R?</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#what-is-coding"><i class="fa fa-check"></i><b>1.1.2</b> What is coding?</a></li>
<li class="chapter" data-level="1.1.3" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#conventions-of-the-course-and-this-reader"><i class="fa fa-check"></i><b>1.1.3</b> Conventions of the course (and this reader)</a></li>
<li class="chapter" data-level="1.1.4" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#things-youll-need"><i class="fa fa-check"></i><b>1.1.4</b> Things You’ll Need</a></li>
<li class="chapter" data-level="1.1.5" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#introduction-to-rstudio"><i class="fa fa-check"></i><b>1.1.5</b> Introduction to RStudio</a></li>
<li class="chapter" data-level="1.1.6" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#your-first-program"><i class="fa fa-check"></i><b>1.1.6</b> Your First Program</a></li>
<li class="chapter" data-level="1.1.7" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#the-iris-dataset"><i class="fa fa-check"></i><b>1.1.7</b> The iris Dataset</a></li>
<li class="chapter" data-level="1.1.8" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#graphing-with-r"><i class="fa fa-check"></i><b>1.1.8</b> Graphing with R</a></li>
<li class="chapter" data-level="1.1.9" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#the-tidyverse-package"><i class="fa fa-check"></i><b>1.1.9</b> The Tidyverse Package</a></li>
<li class="chapter" data-level="1.1.10" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#ggplot2"><i class="fa fa-check"></i><b>1.1.10</b> ggplot2</a></li>
<li class="chapter" data-level="1.1.11" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#facetting"><i class="fa fa-check"></i><b>1.1.11</b> Facetting</a></li>
<li class="chapter" data-level="1.1.12" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#diamonds"><i class="fa fa-check"></i><b>1.1.12</b> diamonds</a></li>
<li class="chapter" data-level="1.1.13" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#other-popular-geoms"><i class="fa fa-check"></i><b>1.1.13</b> Other Popular Geoms</a></li>
<li class="chapter" data-level="1.1.14" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#designing-good-graphics"><i class="fa fa-check"></i><b>1.1.14</b> Designing Good Graphics</a></li>
<li class="chapter" data-level="1.1.15" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#saving-your-graphics"><i class="fa fa-check"></i><b>1.1.15</b> Saving Your Graphics</a></li>
<li class="chapter" data-level="1.1.16" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#more-resources"><i class="fa fa-check"></i><b>1.1.16</b> More Resources</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#exercises"><i class="fa fa-check"></i><b>1.2</b> Exercises</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#calculate-the-following"><i class="fa fa-check"></i><b>1.2.1</b> Calculate the following:</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#graph-the-following"><i class="fa fa-check"></i><b>1.2.2</b> Graph the following:</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#use-a-new-dataset"><i class="fa fa-check"></i><b>1.2.3</b> Use a new dataset:</a></li>
<li class="chapter" data-level="1.2.4" data-path="introduction-to-r-and-data-visualization.html"><a href="introduction-to-r-and-data-visualization.html#looking-ahead"><i class="fa fa-check"></i><b>1.2.4</b> Looking ahead:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html"><i class="fa fa-check"></i><b>2</b> R Functions and Workflow</a><ul>
<li class="chapter" data-level="2.1" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#workflow"><i class="fa fa-check"></i><b>2.1</b> Workflow</a><ul>
<li class="chapter" data-level="2.1.1" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#scripts"><i class="fa fa-check"></i><b>2.1.1</b> Scripts</a></li>
<li class="chapter" data-level="2.1.2" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#notebooks"><i class="fa fa-check"></i><b>2.1.2</b> Notebooks</a></li>
<li class="chapter" data-level="2.1.3" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#memory-objects-and-names"><i class="fa fa-check"></i><b>2.1.3</b> Memory, Objects, and Names</a></li>
<li class="chapter" data-level="2.1.4" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#dataframes-and-transformations"><i class="fa fa-check"></i><b>2.1.4</b> Dataframes and Transformations</a></li>
<li class="chapter" data-level="2.1.5" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#the-pipe"><i class="fa fa-check"></i><b>2.1.5</b> The Pipe</a></li>
<li class="chapter" data-level="2.1.6" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#data-transformations"><i class="fa fa-check"></i><b>2.1.6</b> Data Transformations</a></li>
<li class="chapter" data-level="2.1.7" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#working-with-groups"><i class="fa fa-check"></i><b>2.1.7</b> Working with Groups</a></li>
<li class="chapter" data-level="2.1.8" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#missing-values"><i class="fa fa-check"></i><b>2.1.8</b> Missing Values</a></li>
<li class="chapter" data-level="2.1.9" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#count-data"><i class="fa fa-check"></i><b>2.1.9</b> Count Data</a></li>
<li class="chapter" data-level="2.1.10" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#oddballs"><i class="fa fa-check"></i><b>2.1.10</b> Oddballs</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#r-functions-and-workflow-exercises"><i class="fa fa-check"></i><b>2.2</b> R Functions and Workflow Exercises</a><ul>
<li class="chapter" data-level="2.2.1" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#do-the-following"><i class="fa fa-check"></i><b>2.2.1</b> Do the following:</a></li>
<li class="chapter" data-level="2.2.2" data-path="r-functions-and-workflow.html"><a href="r-functions-and-workflow.html#work-with-other-datasets"><i class="fa fa-check"></i><b>2.2.2</b> Work with other datasets:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html"><i class="fa fa-check"></i><b>3</b> Basic Statistics (Using R)</a><ul>
<li class="chapter" data-level="3.1" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#purpose-of-the-unit"><i class="fa fa-check"></i><b>3.1</b> Purpose of the Unit</a></li>
<li class="chapter" data-level="3.2" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#definitions"><i class="fa fa-check"></i><b>3.2</b> Definitions</a><ul>
<li class="chapter" data-level="3.2.1" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#data-concepts"><i class="fa fa-check"></i><b>3.2.1</b> Data Concepts</a></li>
<li class="chapter" data-level="3.2.2" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#statistical-terms"><i class="fa fa-check"></i><b>3.2.2</b> Statistical Terms</a></li>
<li class="chapter" data-level="3.2.3" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#models-and-tests"><i class="fa fa-check"></i><b>3.2.3</b> Models and Tests</a></li>
<li class="chapter" data-level="3.2.4" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#how-well-compare-models"><i class="fa fa-check"></i><b>3.2.4</b> How We’ll Compare Models</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="basic-statistics-using-r.html"><a href="basic-statistics-using-r.html#examples"><i class="fa fa-check"></i><b>3.3</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html"><i class="fa fa-check"></i><b>4</b> Introductory Data Analysis</a><ul>
<li class="chapter" data-level="4.1" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>4.1</b> Exploratory Data Analysis</a><ul>
<li class="chapter" data-level="4.1.1" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#gapminder"><i class="fa fa-check"></i><b>4.1.1</b> gapminder</a></li>
<li class="chapter" data-level="4.1.2" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#describing-your-data"><i class="fa fa-check"></i><b>4.1.2</b> Describing Your Data</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#statistical-tests-and-regressions"><i class="fa fa-check"></i><b>4.2</b> Statistical Tests and Regressions</a></li>
<li class="chapter" data-level="4.3" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#functional-programming"><i class="fa fa-check"></i><b>4.3</b> Functional Programming</a><ul>
<li class="chapter" data-level="4.3.1" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#column-names"><i class="fa fa-check"></i><b>4.3.1</b> Column Names</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#modeling"><i class="fa fa-check"></i><b>4.4</b> Modeling</a></li>
<li class="chapter" data-level="4.5" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#mixed-models"><i class="fa fa-check"></i><b>4.5</b> Mixed Models</a></li>
<li class="chapter" data-level="4.6" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#conclusion"><i class="fa fa-check"></i><b>4.6</b> Conclusion</a></li>
<li class="chapter" data-level="4.7" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#exercises-1"><i class="fa fa-check"></i><b>4.7</b> Exercises</a><ul>
<li class="chapter" data-level="4.7.1" data-path="introductory-data-analysis.html"><a href="introductory-data-analysis.html#answer-the-following"><i class="fa fa-check"></i><b>4.7.1</b> Answer the following:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html"><i class="fa fa-check"></i><b>5</b> Functions and Scripting</a><ul>
<li class="chapter" data-level="5.1" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#writing-functions"><i class="fa fa-check"></i><b>5.1</b> Writing Functions</a><ul>
<li class="chapter" data-level="5.1.1" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#our-first-function"><i class="fa fa-check"></i><b>5.1.1</b> Our First Function</a></li>
<li class="chapter" data-level="5.1.2" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#returns"><i class="fa fa-check"></i><b>5.1.2</b> Returns</a></li>
<li class="chapter" data-level="5.1.3" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#more-complicated-functions"><i class="fa fa-check"></i><b>5.1.3</b> More Complicated Functions</a></li>
<li class="chapter" data-level="5.1.4" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#about-names"><i class="fa fa-check"></i><b>5.1.4</b> About Names…</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#conditional-statements"><i class="fa fa-check"></i><b>5.2</b> Conditional Statements</a><ul>
<li class="chapter" data-level="5.2.1" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#stops"><i class="fa fa-check"></i><b>5.2.1</b> Stops</a></li>
<li class="chapter" data-level="5.2.2" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#function-dependencies"><i class="fa fa-check"></i><b>5.2.2</b> Function Dependencies</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#saving-and-loading-functions"><i class="fa fa-check"></i><b>5.3</b> Saving and Loading Functions</a></li>
<li class="chapter" data-level="5.4" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#loops"><i class="fa fa-check"></i><b>5.4</b> Loops</a></li>
<li class="chapter" data-level="5.5" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#mapping-functions"><i class="fa fa-check"></i><b>5.5</b> Mapping Functions</a></li>
<li class="chapter" data-level="5.6" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#more-information"><i class="fa fa-check"></i><b>5.6</b> More Information</a></li>
<li class="chapter" data-level="5.7" data-path="functions-and-scripting.html"><a href="functions-and-scripting.html#exercises-2"><i class="fa fa-check"></i><b>5.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html"><i class="fa fa-check"></i><b>6</b> More Complicated Analyses</a><ul>
<li class="chapter" data-level="6.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#work-in-progress"><i class="fa fa-check"></i><b>6.1</b> Work in Progress</a></li>
<li class="chapter" data-level="6.2" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#other-datasets"><i class="fa fa-check"></i><b>6.2</b> Other Datasets</a><ul>
<li class="chapter" data-level="6.2.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#importing-your-own-data"><i class="fa fa-check"></i><b>6.2.1</b> Importing Your Own Data</a></li>
<li class="chapter" data-level="6.2.2" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#exporting-data"><i class="fa fa-check"></i><b>6.2.2</b> Exporting Data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#data-exploration"><i class="fa fa-check"></i><b>6.3</b> Data Exploration</a></li>
<li class="chapter" data-level="6.4" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#modeling-winners"><i class="fa fa-check"></i><b>6.4</b> Modeling Winners</a></li>
<li class="chapter" data-level="6.5" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#logistic-models"><i class="fa fa-check"></i><b>6.5</b> Logistic Models</a></li>
<li class="chapter" data-level="6.6" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#modelling-metrics"><i class="fa fa-check"></i><b>6.6</b> Modelling Metrics</a><ul>
<li class="chapter" data-level="6.6.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#pseudo-r2"><i class="fa fa-check"></i><b>6.6.1</b> Pseudo-R<sup>2</sup></a></li>
<li class="chapter" data-level="6.6.2" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#area-under-the-roc-curve-auc"><i class="fa fa-check"></i><b>6.6.2</b> Area Under the ROC Curve (AUC)</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#model-comparisons"><i class="fa fa-check"></i><b>6.7</b> Model Comparisons</a></li>
<li class="chapter" data-level="6.8" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#auc"><i class="fa fa-check"></i><b>6.8</b> AUC</a><ul>
<li class="chapter" data-level="6.8.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#aic"><i class="fa fa-check"></i><b>6.8.1</b> AIC</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#more-complicated-analyses-1"><i class="fa fa-check"></i><b>6.9</b> More Complicated Analyses</a></li>
<li class="chapter" data-level="6.10" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#model-selection"><i class="fa fa-check"></i><b>6.10</b> Model Selection:</a><ul>
<li class="chapter" data-level="6.10.1" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#detour-another-way"><i class="fa fa-check"></i><b>6.10.1</b> Detour: Another Way</a></li>
<li class="chapter" data-level="6.10.2" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#the-better-faster-way"><i class="fa fa-check"></i><b>6.10.2</b> The Better (…Faster) Way</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="more-complicated-analyses.html"><a href="more-complicated-analyses.html#relational-data"><i class="fa fa-check"></i><b>6.11</b> Relational Data</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html"><i class="fa fa-check"></i><b>7</b> Achieving Graphical Excellence</a><ul>
<li class="chapter" data-level="7.1" data-path="achieving-graphical-excellence.html"><a href="achieving-graphical-excellence.html#work-in-progress-1"><i class="fa fa-check"></i><b>7.1</b> Work in Progress</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Data Exploration and Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="more-complicated-analyses" class="section level1">
<h1><span class="header-section-number">6</span> More Complicated Analyses</h1>
<div id="work-in-progress" class="section level2">
<h2><span class="header-section-number">6.1</span> Work in Progress</h2>
</div>
<div id="other-datasets" class="section level2">
<h2><span class="header-section-number">6.2</span> Other Datasets</h2>
<div id="importing-your-own-data" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Importing Your Own Data</h3>
<p>So far in this course, we’ve been working exclusively with the data pre-available in R and a few of the packages we’ve taken advantage of. While this is a good way to learn R, at some point you may want to use your own data for analysis.</p>
<p>Luckily, R has a number of functions used to import data from external files. To demonstrate these, I’ll be using datasets located <a href="https://github.com/mikemahoney218/Unit6Data">on GitHub</a>, in the “Datasets” folder. You don’t necessarily need to download these files - but we’ll be using these for demonstration throughout this unit.</p>
<p>These datasets are from the website <a href="https://www.kaggle.com/">Kaggle</a>, where a number of data professionals share methods and datasets. Specifically, we’ll be working with two datasets concerning <a href="https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results">all Olympic athletes from the first 120 years of the game</a>. Additionally, we’ll use data on <a href="https://www.kaggle.com/drgilermo/nba-players-stats-20142015">NBA athletes from the 2014-2015 season</a>. I’m not a huge sports guy myself, but there’s a huge amount of sports-related data available publicly online, so it’s a good tool for our analyses.</p>
<p>We’re going to be assuming that your data are located in the same folder as your script - this is usually the easiest way to manage datasets. Otherwise, you’ll have to wrestle a little with using relative pathways and directory names - Hadley Wickham explains these in more detail here.</p>
<p>In order to do this, we’ll be using the <code>readr</code> package, which is included in the base tidyverse:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)</code></pre></div>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 3.0.0     v purrr   0.2.4
## v tibble  1.4.2     v dplyr   0.7.4
## v tidyr   0.8.0     v stringr 1.3.0
## v readr   1.1.1     v forcats 0.3.0</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<p>All the datasets included in our example use different <em>delimiters</em> - the character that tells R (or Excel, or whatever program you’re using) where one column stops and the next one begins. No matter what your delimiter is, we can parse the file using <code>read_delim()</code> - the first argument is the filename to read, while the second is the delimiter used. For instance, our text file is tab delimited - and since tabs are represented in R as <code>\t</code>, we’ll tell <code>read_delim()</code> to use that as a delimiter:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">NOCRegions &lt;-<span class="st"> </span><span class="kw">read_delim</span>(<span class="st">&quot;noc_regions.txt&quot;</span>, <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   NOC = col_character(),
##   region = col_character(),
##   notes = col_character()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">NOCRegions</code></pre></div>
<pre><code>## # A tibble: 230 x 3
##    NOC   region      notes               
##    &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;               
##  1 AFG   Afghanistan &lt;NA&gt;                
##  2 AHO   Curacao     Netherlands Antilles
##  3 ALB   Albania     &lt;NA&gt;                
##  4 ALG   Algeria     &lt;NA&gt;                
##  5 AND   Andorra     &lt;NA&gt;                
##  6 ANG   Angola      &lt;NA&gt;                
##  7 ANT   Antigua     Antigua and Barbuda 
##  8 ANZ   Australia   Australasia         
##  9 ARG   Argentina   &lt;NA&gt;                
## 10 ARM   Armenia     &lt;NA&gt;                
## # ... with 220 more rows</code></pre>
<p>We can do the same thing with documents that have comma separated values (known as CSVs):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents &lt;-<span class="st"> </span><span class="kw">read_delim</span>(<span class="st">&quot;athlete_events.csv&quot;</span>, <span class="st">&quot;,&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   ID = col_integer(),
##   Name = col_character(),
##   Sex = col_character(),
##   Age = col_integer(),
##   Height = col_integer(),
##   Weight = col_double(),
##   NOC = col_character(),
##   Games = col_character(),
##   Year = col_integer(),
##   Season = col_character(),
##   Sport = col_character(),
##   Event = col_character(),
##   Medal = col_character()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents</code></pre></div>
<pre><code>## # A tibble: 271,116 x 13
##       ID Name    Sex     Age Height Weight NOC   Games   Year Season Sport
##    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt; &lt;int&gt;  &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;int&gt; &lt;chr&gt;  &lt;chr&gt;
##  1     1 A Diji~ M        24    180    80. CHN   1992 ~  1992 Summer Bask~
##  2     2 A Lamu~ M        23    170    60. CHN   2012 ~  2012 Summer Judo 
##  3     3 Gunnar~ M        24     NA    NA  DEN   1920 ~  1920 Summer Foot~
##  4     4 Edgar ~ M        34     NA    NA  DEN   1900 ~  1900 Summer Tug-~
##  5     5 Christ~ F        21    185    82. NED   1988 ~  1988 Winter Spee~
##  6     5 Christ~ F        21    185    82. NED   1988 ~  1988 Winter Spee~
##  7     5 Christ~ F        25    185    82. NED   1992 ~  1992 Winter Spee~
##  8     5 Christ~ F        25    185    82. NED   1992 ~  1992 Winter Spee~
##  9     5 Christ~ F        27    185    82. NED   1994 ~  1994 Winter Spee~
## 10     5 Christ~ F        27    185    82. NED   1994 ~  1994 Winter Spee~
## # ... with 271,106 more rows, and 2 more variables: Event &lt;chr&gt;,
## #   Medal &lt;chr&gt;</code></pre>
<p>(You may have noticed that took a second to load - at least, if your computer is middle-of-the-road. This dataset has 271,116 rows - even more than our <code>diamonds</code> dataset - so analyses might take slightly longer with it. Imagine how long “big data” problems would take on your computer, when datasets have several million rows of observations!)</p>
<p>However, <code>readr</code> also includes a pretty good tool specifically for CSV files:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;athlete_events.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   ID = col_integer(),
##   Name = col_character(),
##   Sex = col_character(),
##   Age = col_integer(),
##   Height = col_integer(),
##   Weight = col_double(),
##   NOC = col_character(),
##   Games = col_character(),
##   Year = col_integer(),
##   Season = col_character(),
##   Sport = col_character(),
##   Event = col_character(),
##   Medal = col_character()
## )</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents</code></pre></div>
<pre><code>## # A tibble: 271,116 x 13
##       ID Name    Sex     Age Height Weight NOC   Games   Year Season Sport
##    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt; &lt;int&gt;  &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;int&gt; &lt;chr&gt;  &lt;chr&gt;
##  1     1 A Diji~ M        24    180    80. CHN   1992 ~  1992 Summer Bask~
##  2     2 A Lamu~ M        23    170    60. CHN   2012 ~  2012 Summer Judo 
##  3     3 Gunnar~ M        24     NA    NA  DEN   1920 ~  1920 Summer Foot~
##  4     4 Edgar ~ M        34     NA    NA  DEN   1900 ~  1900 Summer Tug-~
##  5     5 Christ~ F        21    185    82. NED   1988 ~  1988 Winter Spee~
##  6     5 Christ~ F        21    185    82. NED   1988 ~  1988 Winter Spee~
##  7     5 Christ~ F        25    185    82. NED   1992 ~  1992 Winter Spee~
##  8     5 Christ~ F        25    185    82. NED   1992 ~  1992 Winter Spee~
##  9     5 Christ~ F        27    185    82. NED   1994 ~  1994 Winter Spee~
## 10     5 Christ~ F        27    185    82. NED   1994 ~  1994 Winter Spee~
## # ... with 271,106 more rows, and 2 more variables: Event &lt;chr&gt;,
## #   Medal &lt;chr&gt;</code></pre>
<p>Now, <code>readr</code> doesn’t have native support for more complicated files, like Excel files. Philosphically, you shouldn’t store data in Excel format for long periods of time - we have no idea how long Microsoft will be around for, and the encoding used by Excel may someday disappear and take your data with it. CSVs are generally preferred for long-term data storage, as they’re easy to understand visually and are easily parsed by computers.</p>
<p>However, data entry is much easier in Excel, and plenty of data professionals still use the format. Luckily, there’s a package - <code>readxl</code> - designed to parse these types of files:</p>
<pre><code>install.packages(&quot;readxl&quot;)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(readxl)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">NBAStats &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;players_stats.xlsx&quot;</span>)
NBAStats</code></pre></div>
<pre><code>## # A tibble: 490 x 34
##    Name     `Games Played`   MIN   PTS   FGM   FGA `FG%` `3PM` `3PA` `3P%`
##    &lt;chr&gt;             &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 AJ Price            26.  324.  133.   51.  137.  37.2   15.   57.  26.3
##  2 Aaron B~            82. 1885.  954.  344.  817.  42.1  121.  313.  38.7
##  3 Aaron G~            47.  797.  243.   93.  208.  44.7   13.   48.  27.1
##  4 Adreian~            32.  740.  213.   91.  220.  41.4    1.    9.  11.1
##  5 Al Horf~            76. 2318. 1156.  519.  965.  53.8   11.   36.  30.6
##  6 Al Jeff~            65. 1992. 1082.  486. 1010.  48.1    2.    5.  40.0
##  7 Alan An~            74. 1744.  545.  195.  440.  44.3   73.  210.  34.8
##  8 Alec Bu~            27.  899.  374.  121.  300.  40.3   26.   68.  38.2
##  9 Alex Ki~             5.   14.    4.    1.    4.  25.0    0.    0.   0. 
## 10 Alex Len            69. 1518.  432.  179.  353.  50.7    1.    3.  33.3
## # ... with 480 more rows, and 24 more variables: FTM &lt;dbl&gt;, FTA &lt;dbl&gt;,
## #   `FT%` &lt;dbl&gt;, OREB &lt;dbl&gt;, DREB &lt;dbl&gt;, REB &lt;dbl&gt;, AST &lt;dbl&gt;, STL &lt;dbl&gt;,
## #   BLK &lt;dbl&gt;, TOV &lt;dbl&gt;, PF &lt;dbl&gt;, EFF &lt;dbl&gt;, `AST/TOV` &lt;dbl&gt;,
## #   `STL/TOV` &lt;dbl&gt;, Age &lt;dbl&gt;, Birth_Place &lt;chr&gt;, Birthdate &lt;dttm&gt;,
## #   Collage &lt;chr&gt;, Experience &lt;chr&gt;, Height &lt;dbl&gt;, Pos &lt;chr&gt;, Team &lt;chr&gt;,
## #   Weight &lt;dbl&gt;, BMI &lt;dbl&gt;</code></pre>
<p>You’ll also notice that RStudio has an “import dataset” button in the top right corner, which makes use of both the <code>readr</code> and <code>readxl</code> packages. This button lets you point and click your way through data import, and then copy the code into your script. It’s a great resource for beginners!</p>
</div>
<div id="exporting-data" class="section level3">
<h3><span class="header-section-number">6.2.2</span> Exporting Data</h3>
<p>Writing data to a file is also pretty painless using <code>readr</code>. There are as many options for delimiters as before - you can use <code>write_delim()</code> to specify which you want to use with your data - but more commonly data is imported and exported as CSV files using <code>write_csv()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">write_csv</span>(AthleteEvents, <span class="st">&quot;athlete_events.csv&quot;</span>)</code></pre></div>
<p>Note that, like all other <code>tidyverse</code> functions, the dataset is the first thing you specify.</p>
</div>
</div>
<div id="data-exploration" class="section level2">
<h2><span class="header-section-number">6.3</span> Data Exploration</h2>
<p>Let’s put <code>NBAStats</code> off to the side for a moment, and look at our other two datasets. <code>AthleteEvents</code> is a list of all olympic competitors from 1892 to 2016, including basic statistics about each and any medals they may have won. <code>NOCRegions</code>, meanwhile, maps codes used by the National Olympic Committee (NOC) to the countries they represent.</p>
<p>We can get a sense of the variables this dataset measures using <code>psych::describe()</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">psych<span class="op">::</span><span class="kw">describe</span>(AthleteEvents)</code></pre></div>
<pre><code>## Warning in psych::describe(AthleteEvents): NAs introduced by coercion

## Warning in psych::describe(AthleteEvents): NAs introduced by coercion

## Warning in psych::describe(AthleteEvents): NAs introduced by coercion

## Warning in psych::describe(AthleteEvents): NAs introduced by coercion

## Warning in psych::describe(AthleteEvents): NAs introduced by coercion

## Warning in psych::describe(AthleteEvents): NAs introduced by coercion

## Warning in psych::describe(AthleteEvents): NAs introduced by coercion

## Warning in psych::describe(AthleteEvents): NAs introduced by coercion</code></pre>
<pre><code>## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf</code></pre>
<pre><code>## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf

## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf</code></pre>
<pre><code>##         vars      n     mean       sd median  trimmed      mad  min    max
## ID         1 271116 68248.95 39022.29  68205 68290.17 50019.96    1 135571
## Name*      2 271116      NaN       NA     NA      NaN       NA  Inf   -Inf
## Sex*       3 271116      NaN       NA     NA      NaN       NA  Inf   -Inf
## Age        4 261642    25.56     6.39     24    24.87     4.45   10     97
## Height     5 210945   175.34    10.52    175   175.31    10.38  127    226
## Weight     6 208241    70.70    14.35     70    69.90    13.34   25    214
## NOC*       7 271116      NaN       NA     NA      NaN       NA  Inf   -Inf
## Games*     8 271116      NaN       NA     NA      NaN       NA  Inf   -Inf
## Year       9 271116  1978.38    29.88   1988  1981.65    29.65 1896   2016
## Season*   10 271116      NaN       NA     NA      NaN       NA  Inf   -Inf
## Sport*    11 271116      NaN       NA     NA      NaN       NA  Inf   -Inf
## Event*    12 271116      NaN       NA     NA      NaN       NA  Inf   -Inf
## Medal*    13  39783      NaN       NA     NA      NaN       NA  Inf   -Inf
##          range  skew kurtosis    se
## ID      135570  0.00    -1.20 74.94
## Name*     -Inf    NA       NA    NA
## Sex*      -Inf    NA       NA    NA
## Age         87  1.75     6.27  0.01
## Height      99  0.02     0.18  0.02
## Weight     189  0.80     2.02  0.03
## NOC*      -Inf    NA       NA    NA
## Games*    -Inf    NA       NA    NA
## Year       120 -0.82    -0.21  0.06
## Season*   -Inf    NA       NA    NA
## Sport*    -Inf    NA       NA    NA
## Event*    -Inf    NA       NA    NA
## Medal*    -Inf    NA       NA    NA</code></pre>
<p>Wow, R didn’t like that!</p>
<p>R didn’t know how to calculate most of the fields in <code>describe()</code> for character vectors. We can try that process again with only the numeric columns by using <code>select_if()</code> from <code>dplyr</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">psych<span class="op">::</span><span class="kw">describe</span>(<span class="kw">select_if</span>(AthleteEvents, is.numeric))</code></pre></div>
<pre><code>##        vars      n     mean       sd median  trimmed      mad  min    max
## ID        1 271116 68248.95 39022.29  68205 68290.17 50019.96    1 135571
## Age       2 261642    25.56     6.39     24    24.87     4.45   10     97
## Height    3 210945   175.34    10.52    175   175.31    10.38  127    226
## Weight    4 208241    70.70    14.35     70    69.90    13.34   25    214
## Year      5 271116  1978.38    29.88   1988  1981.65    29.65 1896   2016
##         range  skew kurtosis    se
## ID     135570  0.00    -1.20 74.94
## Age        87  1.75     6.27  0.01
## Height     99  0.02     0.18  0.02
## Weight    189  0.80     2.02  0.03
## Year      120 -0.82    -0.21  0.06</code></pre>
<p>When I see this output, TK things catch my eye:</p>
<ul>
<li>We knew we were missing observations, but wow, we’re missing observations. Over 60,000 athletes have no weight listed, while over 50,000 don’t have a height.</li>
<li>Mean height is 175.34 while mean weight is 70.7, suggesting that we’re using metric units here</li>
<li>Looking at mean, skew and kurtosis, it seems like we have a lot more athletes in recent years - the distribution is centered around 1978, almost 100 years into our 120 year dataset - and that while an incredible number of athletes are young (25, with a kurtosis of 6.27!), we have plenty of older competitors.</li>
</ul>
<p>If we want to get a sense of correlations in the data, we can try using <code>pairs()</code> again - but be warned, this one might take a while due to the size of the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pairs</span>(<span class="kw">select_if</span>(AthleteEvents, is.numeric))</code></pre></div>
<p><img src="06_More_Complicated_Analyses_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>(Pop quiz for the history nerds: what are those vertical bars in the <code>Year</code> column?)</p>
<p>That’s a little chaotic, but we can still see trends nicely enough. It looks like height and weight have increased in variance over the years, probably due to the increased number of athletes overall. Height and weight look tightly correlated, as do age and the other statistics, interestingly enough. If we look at the actual correlation coefficients, we can see these trends numerically. We’re going to have to remove the NAs manually, first, using dplyr’s <code>drop_na</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select_if</span>(is.numeric) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">drop_na</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">cor</span>()</code></pre></div>
<pre><code>##                  ID          Age      Height       Weight        Year
## ID      1.000000000 -0.002100308 -0.01219033 -0.009038648 0.007066518
## Age    -0.002100308  1.000000000  0.14168449  0.212040722 0.089142499
## Height -0.012190329  0.141684490  1.00000000  0.796572579 0.048141525
## Weight -0.009038648  0.212040722  0.79657258  1.000000000 0.022175179
## Year    0.007066518  0.089142499  0.04814153  0.022175179 1.000000000</code></pre>
<p>So we’re right in thinking that height and weight are correlated, but maybe not age. It is interesting to see that year is more correlated with age than any other variable!</p>
<p>Moving back to the full dataset, I have a few other questions I want to ask. First off, when did women start competing? It would be useful to know if our gender distributions have significantly different lengths. Let’s <code>count()</code> the number of male and female athletes per year:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(Year, Sex)</code></pre></div>
<pre><code>## # A tibble: 69 x 3
##     Year Sex       n
##    &lt;int&gt; &lt;chr&gt; &lt;int&gt;
##  1  1896 M       380
##  2  1900 F        33
##  3  1900 M      1903
##  4  1904 F        16
##  5  1904 M      1285
##  6  1906 F        11
##  7  1906 M      1722
##  8  1908 F        47
##  9  1908 M      3054
## 10  1912 F        87
## # ... with 59 more rows</code></pre>
<p>The first women appear in 1900! That’s very cool.</p>
<p>I do wonder if the male or female athletes have it harder - that is, are there more male or female medal recipients, as a proportion of the whole? For instance, if fewer countries send female participants, each participant might be more statistically more likely to win.</p>
<p>We can eyeball this by calculating the percentage of each gender who hold each type of medal, out of the total number of athletes who have participated. To do so, we’ll count the number of recipients of each type of medal, rename the <code>NA</code> medal value “none”, group our data by sex, and then divide the number of people who have received each medal by the total number of contestants:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(Sex, Medal) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">replace_na</span>(<span class="kw">list</span>(<span class="dt">Medal =</span> <span class="ot">NA</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Sex) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">PercentReceiving =</span> n <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(n))</code></pre></div>
<pre><code>## # A tibble: 8 x 4
## # Groups:   Sex [2]
##   Sex   Medal       n PercentReceiving
##   &lt;chr&gt; &lt;chr&gt;   &lt;int&gt;            &lt;dbl&gt;
## 1 F     Bronze   3771           0.0506
## 2 F     Gold     3747           0.0503
## 3 F     Silver   3735           0.0501
## 4 F     &lt;NA&gt;    63269           0.849 
## 5 M     Bronze   9524           0.0484
## 6 M     Gold     9625           0.0490
## 7 M     Silver   9381           0.0477
## 8 M     &lt;NA&gt;   168064           0.855</code></pre>
<p>So it looks like women have a tiny edge, but generally speaking, both men and women have a 15% chance of medalling at the Olympics.</p>
</div>
<div id="modeling-winners" class="section level2">
<h2><span class="header-section-number">6.4</span> Modeling Winners</h2>
<p>Personally, I’m interested in predicting if someone will win a medal at the Olympics. We could do this a number of inferential ways - for instance, dropping all the values where an athlete <em>didn’t</em> win, and looking at the summary statistics of the athletes who did:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Medal)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summary</span>(<span class="dt">object =</span> .)</code></pre></div>
<pre><code>##        ID             Name               Sex                 Age       
##  Min.   :     4   Length:39783       Length:39783       Min.   :10.00  
##  1st Qu.: 36494   Class :character   Class :character   1st Qu.:22.00  
##  Median : 68990   Mode  :character   Mode  :character   Median :25.00  
##  Mean   : 69407                                         Mean   :25.93  
##  3rd Qu.:103462                                         3rd Qu.:29.00  
##  Max.   :135563                                         Max.   :73.00  
##                                                         NA&#39;s   :732    
##      Height          Weight           NOC               Games          
##  Min.   :136.0   Min.   : 28.00   Length:39783       Length:39783      
##  1st Qu.:170.0   1st Qu.: 63.00   Class :character   Class :character  
##  Median :178.0   Median : 73.00   Mode  :character   Mode  :character  
##  Mean   :177.6   Mean   : 73.77                                        
##  3rd Qu.:185.0   3rd Qu.: 83.00                                        
##  Max.   :223.0   Max.   :182.00                                        
##  NA&#39;s   :8711    NA&#39;s   :9327                                          
##       Year         Season             Sport              Event          
##  Min.   :1896   Length:39783       Length:39783       Length:39783      
##  1st Qu.:1952   Class :character   Class :character   Class :character  
##  Median :1984   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :1974                                                           
##  3rd Qu.:2002                                                           
##  Max.   :2016                                                           
##                                                                         
##     Medal          
##  Length:39783      
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
## </code></pre>
<p>This doesn’t help us that much - it appears that these athletes are slightly older, taller, and heavier than the whole dataset, but that’s not a lot to go off of when making predictions - no one wants to bet on the oldest and heaviest high jumper.</p>
<p>One way we could try to do this is using our old friend, the <code>lm()</code> tool, with all the data we have. We can make a new binary column <code>Winner</code>, which will be 1 if the athlete won a medal, and then try to model it:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents<span class="op">$</span>Winner &lt;-<span class="st"> </span>AthleteEvents<span class="op">$</span>Medal
AthleteEvents<span class="op">$</span>Winner[<span class="kw">which</span>(<span class="op">!</span><span class="kw">is.na</span>((AthleteEvents<span class="op">$</span>Winner)))] &lt;-<span class="st"> </span><span class="dv">1</span>
AthleteEvents<span class="op">$</span>Winner[<span class="kw">which</span>(<span class="kw">is.na</span>(AthleteEvents<span class="op">$</span>Winner))] &lt;-<span class="st"> </span><span class="dv">0</span>
AthleteEvents<span class="op">$</span>Winner &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(AthleteEvents<span class="op">$</span>Winner)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteEvents <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">replace_na</span>(<span class="kw">list</span>(<span class="dt">Winner =</span> <span class="dv">0</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">lm</span>(Winner <span class="op">~</span><span class="st"> </span>ID <span class="op">*</span><span class="st"> </span>Name <span class="op">*</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight <span class="op">*</span><span class="st"> </span>NOC <span class="op">*</span><span class="st"> </span>Games <span class="op">*</span><span class="st"> </span>Year <span class="op">*</span><span class="st"> </span>Season <span class="op">*</span><span class="st"> </span>Sport <span class="op">*</span><span class="st"> </span>Event, <span class="dt">data =</span> .)</code></pre></div>
<pre><code>## Error: cannot allocate vector of size 72.4 Gb</code></pre>
<p>But R doesn’t like that much.</p>
<p>This process is pretty excessive - we’re asking R to calculate a <em>lot</em> of stuff - and also has the downside of probably being <em>too</em> specific. After all, if we tell R what ID each athlete has, plus the year and the event, it can tell 100% of the time who won the medal!</p>
<p>Instead, we want to be able to guess what <em>traits</em> make someone more likely to win. As such, we should only test the variables that we think are scientifically relevant - most likely, things like their age, height, and weight. If we make a model more like that:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteLinearModel &lt;-<span class="st"> </span><span class="kw">lm</span>(Winner <span class="op">~</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> AthleteEvents) 

<span class="kw">summary</span>(AthleteLinearModel)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Winner ~ Age * Height * Weight, data = AthleteEvents)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.5264 -0.1570 -0.1327 -0.1113  0.9327 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)        2.833e-01  2.156e-01   1.314  0.18884   
## Age                1.125e-02  8.985e-03   1.252  0.21047   
## Height            -2.668e-03  1.278e-03  -2.088  0.03676 * 
## Weight            -1.735e-03  3.201e-03  -0.542  0.58783   
## Age:Height        -4.743e-06  5.274e-05  -0.090  0.92834   
## Age:Weight        -3.489e-04  1.294e-04  -2.696  0.00701 **
## Height:Weight      3.429e-05  1.791e-05   1.915  0.05549 . 
## Age:Height:Weight  1.221e-06  7.231e-07   1.689  0.09125 . 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3517 on 206157 degrees of freedom
##   (64951 observations deleted due to missingness)
## Multiple R-squared:  0.01027,    Adjusted R-squared:  0.01024 
## F-statistic: 305.6 on 7 and 206157 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="logistic-models" class="section level2">
<h2><span class="header-section-number">6.5</span> Logistic Models</h2>
<p>Wow! Every single term in our model is significant, but the R<sup>2</sup> is horrible!</p>
<p>As for why that might be, let’s visualize our response variable against one of its predictors - again, this might take a second to run:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(AthleteEvents, <span class="kw">aes</span>(Height, Winner)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<pre><code>## Warning: Removed 60171 rows containing missing values (geom_point).</code></pre>
<p><img src="06_More_Complicated_Analyses_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>This here is the root of our problem - we’re trying to model a binary outcome (a yes or no, a medal or not) with a straight line, which is useless. This sort of problem comes up all the time in real world situations - in science, whether or not a trap will catch something, or in business, whether or not a customer will click.</p>
<p>Instead, we can choose to use a <em>logistic model</em>, one of the types of <em>generalized linear models</em> from chapter 3. These models serve to measure the probability of a binary event - while a linear model will tell you the value of your response variable, logistic models will tell you the probability your response variable is 1.</p>
<p>R convieniently has a function <code>glm()</code> for doing exactly this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteLogisticModel &lt;-<span class="st"> </span><span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> AthleteEvents, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>) 

<span class="kw">summary</span>(AthleteLogisticModel)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Winner ~ Age * Height * Weight, family = &quot;binomial&quot;, 
##     data = AthleteEvents)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3873  -0.5831  -0.5351  -0.4870   2.3375  
## 
## Coefficients:
##                     Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)       -4.023e+00  1.815e+00  -2.216  0.02668 * 
## Age                1.228e-01  7.358e-02   1.669  0.09514 . 
## Height            -2.067e-03  1.062e-02  -0.195  0.84561   
## Weight             3.083e-02  2.616e-02   1.179  0.23849   
## Age:Height        -2.261e-04  4.275e-04  -0.529  0.59699   
## Age:Weight        -3.099e-03  1.036e-03  -2.990  0.00279 **
## Height:Weight      1.595e-05  1.447e-04   0.110  0.91224   
## Age:Height:Weight  1.160e-05  5.731e-06   2.023  0.04303 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 171694  on 206164  degrees of freedom
## Residual deviance: 169703  on 206157  degrees of freedom
##   (64951 observations deleted due to missingness)
## AIC: 169719
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Note that <code>family = &quot;binomial&quot;</code> is necessary to make R compute a logistic model - you can find other possible generalized linear model formats by typing <code>?family</code>.</p>
</div>
<div id="modelling-metrics" class="section level2">
<h2><span class="header-section-number">6.6</span> Modelling Metrics</h2>
<p>Well, our terms are all still significant, which is a good thing - but you’ll notice that we now have no R<sup>2</sup>! That’s because R<sup>2</sup> terms don’t really exist for logistic models, for reasons we won’t go too far into - you can read more on the topic <a href="https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faq-what-are-pseudo-r-squareds/">here</a>. But what we will get into are other methods of evaluating logistic models.</p>
<p>One of the more common methods of comparing logistic models is to use what’s known as a pseudo R<sup>2</sup> value. Unfortunately, there are plenty of different methods to compute these, and you can’t compare R<sup>2</sup> calculated with different formulas to one another.</p>
<div id="pseudo-r2" class="section level3">
<h3><span class="header-section-number">6.6.1</span> Pseudo-R<sup>2</sup></h3>
<p>One package that gives pretty decent results is the <code>pscl</code> package by Simon Jackman. After we install it, we can use the <code>pR2()</code> function to give us some pseudo-R<sup>2</sup> values:</p>
<pre><code>install.packages(&quot;pscl&quot;)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pscl<span class="op">::</span><span class="kw">pR2</span>(AthleteLogisticModel)</code></pre></div>
<pre><code>##           llh       llhNull            G2      McFadden          r2ML 
## -8.485169e+04 -1.130577e+05  5.641209e+04  2.494835e-01  2.393834e-01 
##          r2CU 
##  3.594066e-01</code></pre>
<p>The McFadden R<sup>2</sup> is given as the fourth output from this function, while the Cragg-Uhler R<sup>2</sup> is the last value in the list. Again, these numbers can only be compared against other pseudo-R<sup>2</sup> following the same formula, which limits their versatility.</p>
</div>
<div id="area-under-the-roc-curve-auc" class="section level3">
<h3><span class="header-section-number">6.6.2</span> Area Under the ROC Curve (AUC)</h3>
<p>More common in data analytics is to find the area under the receiver operating curve - abbreviated as AUC. To understand how we get there, let’s first take a look at our model object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteLogisticModel</code></pre></div>
<pre><code>## 
## Call:  glm(formula = Winner ~ Age * Height * Weight, family = &quot;binomial&quot;, 
##     data = AthleteEvents)
## 
## Coefficients:
##       (Intercept)                Age             Height  
##        -4.023e+00          1.228e-01         -2.067e-03  
##            Weight         Age:Height         Age:Weight  
##         3.083e-02         -2.261e-04         -3.099e-03  
##     Height:Weight  Age:Height:Weight  
##         1.595e-05          1.160e-05  
## 
## Degrees of Freedom: 206164 Total (i.e. Null);  206157 Residual
##   (64951 observations deleted due to missingness)
## Null Deviance:       171700 
## Residual Deviance: 169700    AIC: 169700</code></pre>
<p>There’s a lot going on in here! R stores models as <em>list objects</em>, containing a number of elements of different data types. We can get a sense of what’s going on under the hood using <code>str()</code> - that is, asking R to show us the <code>str</code>ucture of the data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(AthleteLogisticModel)</code></pre></div>
<pre><code>## List of 31
##  $ coefficients     : Named num [1:8] -4.023117 0.122794 -0.002067 0.030834 -0.000226 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:8] &quot;(Intercept)&quot; &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot; ...
##  $ residuals        : Named num [1:206165] -1.19 -1.14 -1.21 -1.21 -1.21 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:206165] &quot;1&quot; &quot;2&quot; &quot;5&quot; &quot;6&quot; ...
##  $ fitted.values    : Named num [1:206165] 0.158 0.122 0.171 0.171 0.173 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:206165] &quot;1&quot; &quot;2&quot; &quot;5&quot; &quot;6&quot; ...
##  $ effects          : Named num [1:206165] 277.54 11.65 -40.07 -11.55 -2.84 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:206165] &quot;(Intercept)&quot; &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot; ...
##  $ R                : num [1:8, 1:8] -160 0 0 0 0 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:8] &quot;(Intercept)&quot; &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot; ...
##   .. ..$ : chr [1:8] &quot;(Intercept)&quot; &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot; ...
##  $ rank             : int 8
##  $ qr               :List of 5
##   ..$ qr   : num [1:206165, 1:8] -1.60e+02 2.05e-03 2.36e-03 2.36e-03 2.37e-03 ...
##   .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. .. ..$ : chr [1:206165] &quot;1&quot; &quot;2&quot; &quot;5&quot; &quot;6&quot; ...
##   .. .. ..$ : chr [1:8] &quot;(Intercept)&quot; &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot; ...
##   ..$ rank : int 8
##   ..$ qraux: num [1:8] 1 1 1 1 1 ...
##   ..$ pivot: int [1:8] 1 2 3 4 5 6 7 8
##   ..$ tol  : num 1e-11
##   ..- attr(*, &quot;class&quot;)= chr &quot;qr&quot;
##  $ family           :List of 12
##   ..$ family    : chr &quot;binomial&quot;
##   ..$ link      : chr &quot;logit&quot;
##   ..$ linkfun   :function (mu)  
##   ..$ linkinv   :function (eta)  
##   ..$ variance  :function (mu)  
##   ..$ dev.resids:function (y, mu, wt)  
##   ..$ aic       :function (y, n, mu, wt, dev)  
##   ..$ mu.eta    :function (eta)  
##   ..$ initialize:  expression({  if (NCOL(y) == 1) {  if (is.factor(y))  y &lt;- y != levels(y)[1L]  n &lt;- rep.int(1, nobs)  y[weights =| __truncated__
##   ..$ validmu   :function (mu)  
##   ..$ valideta  :function (eta)  
##   ..$ simulate  :function (object, nsim)  
##   ..- attr(*, &quot;class&quot;)= chr &quot;family&quot;
##  $ linear.predictors: Named num [1:206165] -1.67 -1.98 -1.58 -1.58 -1.57 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:206165] &quot;1&quot; &quot;2&quot; &quot;5&quot; &quot;6&quot; ...
##  $ deviance         : num 169703
##  $ aic              : num 169719
##  $ null.deviance    : num 171694
##  $ iter             : int 4
##  $ weights          : Named num [1:206165] 0.133 0.107 0.142 0.142 0.143 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:206165] &quot;1&quot; &quot;2&quot; &quot;5&quot; &quot;6&quot; ...
##  $ prior.weights    : Named num [1:206165] 1 1 1 1 1 1 1 1 1 1 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:206165] &quot;1&quot; &quot;2&quot; &quot;5&quot; &quot;6&quot; ...
##  $ df.residual      : int 206157
##  $ df.null          : int 206164
##  $ y                : Named num [1:206165] 0 0 0 0 0 0 0 0 0 0 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:206165] &quot;1&quot; &quot;2&quot; &quot;5&quot; &quot;6&quot; ...
##  $ converged        : logi TRUE
##  $ boundary         : logi FALSE
##  $ model            :&#39;data.frame&#39;:   206165 obs. of  4 variables:
##   ..$ Winner: num [1:206165] 0 0 0 0 0 0 0 0 0 0 ...
##   ..$ Age   : int [1:206165] 24 23 21 21 25 25 27 27 31 31 ...
##   ..$ Height: int [1:206165] 180 170 185 185 185 185 185 185 188 188 ...
##   ..$ Weight: num [1:206165] 80 60 82 82 82 82 82 82 75 75 ...
##   ..- attr(*, &quot;terms&quot;)=Classes &#39;terms&#39;, &#39;formula&#39;  language Winner ~ Age * Height * Weight
##   .. .. ..- attr(*, &quot;variables&quot;)= language list(Winner, Age, Height, Weight)
##   .. .. ..- attr(*, &quot;factors&quot;)= int [1:4, 1:7] 0 1 0 0 0 0 1 0 0 0 ...
##   .. .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. .. .. .. ..$ : chr [1:4] &quot;Winner&quot; &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot;
##   .. .. .. .. ..$ : chr [1:7] &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot; &quot;Age:Height&quot; ...
##   .. .. ..- attr(*, &quot;term.labels&quot;)= chr [1:7] &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot; &quot;Age:Height&quot; ...
##   .. .. ..- attr(*, &quot;order&quot;)= int [1:7] 1 1 1 2 2 2 3
##   .. .. ..- attr(*, &quot;intercept&quot;)= int 1
##   .. .. ..- attr(*, &quot;response&quot;)= int 1
##   .. .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; 
##   .. .. ..- attr(*, &quot;predvars&quot;)= language list(Winner, Age, Height, Weight)
##   .. .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:4] &quot;numeric&quot; &quot;numeric&quot; &quot;numeric&quot; &quot;numeric&quot;
##   .. .. .. ..- attr(*, &quot;names&quot;)= chr [1:4] &quot;Winner&quot; &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot;
##   ..- attr(*, &quot;na.action&quot;)=Class &#39;omit&#39;  Named int [1:64951] 3 4 27 28 30 36 37 38 39 40 ...
##   .. .. ..- attr(*, &quot;names&quot;)= chr [1:64951] &quot;3&quot; &quot;4&quot; &quot;27&quot; &quot;28&quot; ...
##  $ na.action        :Class &#39;omit&#39;  Named int [1:64951] 3 4 27 28 30 36 37 38 39 40 ...
##   .. ..- attr(*, &quot;names&quot;)= chr [1:64951] &quot;3&quot; &quot;4&quot; &quot;27&quot; &quot;28&quot; ...
##  $ call             : language glm(formula = Winner ~ Age * Height * Weight, family = &quot;binomial&quot;,      data = AthleteEvents)
##  $ formula          :Class &#39;formula&#39;  language Winner ~ Age * Height * Weight
##   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; 
##  $ terms            :Classes &#39;terms&#39;, &#39;formula&#39;  language Winner ~ Age * Height * Weight
##   .. ..- attr(*, &quot;variables&quot;)= language list(Winner, Age, Height, Weight)
##   .. ..- attr(*, &quot;factors&quot;)= int [1:4, 1:7] 0 1 0 0 0 0 1 0 0 0 ...
##   .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. .. .. ..$ : chr [1:4] &quot;Winner&quot; &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot;
##   .. .. .. ..$ : chr [1:7] &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot; &quot;Age:Height&quot; ...
##   .. ..- attr(*, &quot;term.labels&quot;)= chr [1:7] &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot; &quot;Age:Height&quot; ...
##   .. ..- attr(*, &quot;order&quot;)= int [1:7] 1 1 1 2 2 2 3
##   .. ..- attr(*, &quot;intercept&quot;)= int 1
##   .. ..- attr(*, &quot;response&quot;)= int 1
##   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; 
##   .. ..- attr(*, &quot;predvars&quot;)= language list(Winner, Age, Height, Weight)
##   .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:4] &quot;numeric&quot; &quot;numeric&quot; &quot;numeric&quot; &quot;numeric&quot;
##   .. .. ..- attr(*, &quot;names&quot;)= chr [1:4] &quot;Winner&quot; &quot;Age&quot; &quot;Height&quot; &quot;Weight&quot;
##  $ data             :Classes &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;:   271116 obs. of  14 variables:
##   ..$ ID    : int [1:271116] 1 2 3 4 5 5 5 5 5 5 ...
##   ..$ Name  : chr [1:271116] &quot;A Dijiang&quot; &quot;A Lamusi&quot; &quot;Gunnar Nielsen Aaby&quot; &quot;Edgar Lindenau Aabye&quot; ...
##   ..$ Sex   : chr [1:271116] &quot;M&quot; &quot;M&quot; &quot;M&quot; &quot;M&quot; ...
##   ..$ Age   : int [1:271116] 24 23 24 34 21 21 25 25 27 27 ...
##   ..$ Height: int [1:271116] 180 170 NA NA 185 185 185 185 185 185 ...
##   ..$ Weight: num [1:271116] 80 60 NA NA 82 82 82 82 82 82 ...
##   ..$ NOC   : chr [1:271116] &quot;CHN&quot; &quot;CHN&quot; &quot;DEN&quot; &quot;DEN&quot; ...
##   ..$ Games : chr [1:271116] &quot;1992 Summer&quot; &quot;2012 Summer&quot; &quot;1920 Summer&quot; &quot;1900 Summer&quot; ...
##   ..$ Year  : int [1:271116] 1992 2012 1920 1900 1988 1988 1992 1992 1994 1994 ...
##   ..$ Season: chr [1:271116] &quot;Summer&quot; &quot;Summer&quot; &quot;Summer&quot; &quot;Summer&quot; ...
##   ..$ Sport : chr [1:271116] &quot;Basketball&quot; &quot;Judo&quot; &quot;Football&quot; &quot;Tug-Of-War&quot; ...
##   ..$ Event : chr [1:271116] &quot;Basketball Men&#39;s Basketball&quot; &quot;Judo Men&#39;s Extra-Lightweight&quot; &quot;Football Men&#39;s Football&quot; &quot;Tug-Of-War Men&#39;s Tug-Of-War&quot; ...
##   ..$ Medal : chr [1:271116] NA NA NA &quot;Gold&quot; ...
##   ..$ Winner: num [1:271116] 0 0 0 1 0 0 0 0 0 0 ...
##   ..- attr(*, &quot;spec&quot;)=List of 2
##   .. ..$ cols   :List of 13
##   .. .. ..$ ID    : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_integer&quot; &quot;collector&quot;
##   .. .. ..$ Name  : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_character&quot; &quot;collector&quot;
##   .. .. ..$ Sex   : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_character&quot; &quot;collector&quot;
##   .. .. ..$ Age   : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_integer&quot; &quot;collector&quot;
##   .. .. ..$ Height: list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_integer&quot; &quot;collector&quot;
##   .. .. ..$ Weight: list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_double&quot; &quot;collector&quot;
##   .. .. ..$ NOC   : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_character&quot; &quot;collector&quot;
##   .. .. ..$ Games : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_character&quot; &quot;collector&quot;
##   .. .. ..$ Year  : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_integer&quot; &quot;collector&quot;
##   .. .. ..$ Season: list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_character&quot; &quot;collector&quot;
##   .. .. ..$ Sport : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_character&quot; &quot;collector&quot;
##   .. .. ..$ Event : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_character&quot; &quot;collector&quot;
##   .. .. ..$ Medal : list()
##   .. .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_character&quot; &quot;collector&quot;
##   .. ..$ default: list()
##   .. .. ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;collector_guess&quot; &quot;collector&quot;
##   .. ..- attr(*, &quot;class&quot;)= chr &quot;col_spec&quot;
##  $ offset           : NULL
##  $ control          :List of 3
##   ..$ epsilon: num 1e-08
##   ..$ maxit  : num 25
##   ..$ trace  : logi FALSE
##  $ method           : chr &quot;glm.fit&quot;
##  $ contrasts        : NULL
##  $ xlevels          : Named list()
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;glm&quot; &quot;lm&quot;</code></pre>
<p>There’s a ton going on in there!</p>
<p>Luckily enough, we don’t have to worry about most of it. The two elements I do want to point out, though, are the <code>y</code> and <code>fitted.values</code> columns. <code>y</code> contains our response variable - whether or not an athlete medaled - as a binary value of 1 or 0. <code>fitted.values</code>, meanwhile, stores the probability our model gives of <code>y</code> being 1. We can take advantage of this using the package <code>pROC</code>, which will let us calculate how close our model got. Let’s first install and load <code>pROC</code>:</p>
<pre><code>install.packages(&quot;pROC&quot;)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(pROC)</code></pre></div>
<pre><code>## Type &#39;citation(&quot;pROC&quot;)&#39; for a citation.</code></pre>
<pre><code>## 
## Attaching package: &#39;pROC&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     cov, smooth, var</code></pre>
<p>What we’re going to do now is to build a receiver operating characteristic curve - a ROC - in order to understand graphically exactly what we’re computing. <code>pROC</code> makes that easy, using the function <code>roc()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">LogModelROC &lt;-<span class="st"> </span><span class="kw">roc</span>(AthleteLogisticModel<span class="op">$</span>y, AthleteLogisticModel<span class="op">$</span>fitted.values)</code></pre></div>
<p>We can then plot our ROC object using <code>plot.roc()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot.roc</span>(LogModelROC)</code></pre></div>
<p><img src="06_More_Complicated_Analyses_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>This is cool! What the hell is it?</p>
<p>This is what we mean when we say receiver operating characteristic curve. That light grey line in the middle represents what would happen if we just randomly guessed whether or not each athlete got a medal, using a 50/50 chance. The black line represents how well our model did - everywhere that it’s higher than the grey line, we were more accurate than random chance. We don’t need to worry about exactly what the axes mean (basically, the x axis represents how confident our model is in guessing someone medaled, while the y is how surprised it is about the result), but you can read more for yourself <a href="https://towardsdatascience.com/understanding-auc-roc-curve-68b2303cc9c5">here</a>.</p>
<p>The curve is cool and all, but is hard to interpret. Luckily for us, there’s a single value - similar to R<sup>2</sup> for linear models - which we can use to identify how well our model did. That number is the area under the curve (AUC, sometimes called the c-statistic) that I mentioned earlier, which we can calculate with pROC by printing out our ROC object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">LogModelROC</code></pre></div>
<pre><code>## 
## Call:
## roc.default(response = AthleteLogisticModel$y, predictor = AthleteLogisticModel$fitted.values)
## 
## Data: AthleteLogisticModel$fitted.values in 175984 controls (AthleteLogisticModel$y 0) &lt; 30181 cases (AthleteLogisticModel$y 1).
## Area under the curve: 0.5753</code></pre>
<p>(Note that, if I didn’t assign the ROC object to a name in the first place, this value would have just printed out.)</p>
<p>That number - 0.57 - is our single statistic for how accurate our model is. Generally speaking, models with an AUC of 0.7 are thought of as good models, with 0.8 as great and 0.9 incredible. Ecology can have slightly fuzzier models - predicting the natural world is hard, yo - but even the “random chance” line has an AUC of 0.5 - if your model is close to or below that, it’s pretty much useless.</p>
</div>
</div>
<div id="model-comparisons" class="section level2">
<h2><span class="header-section-number">6.7</span> Model Comparisons</h2>
</div>
<div id="auc" class="section level2">
<h2><span class="header-section-number">6.8</span> AUC</h2>
<p>So while our model is doing better than chance, it’s still not doing great - 0.57 leaves a lot of room to improve. For instance, since we know the sex of each athlete in our dataset, what would happen if we added that variable to our formula?</p>
<p>We can calculate the new formula following all the steps above. I’m also going to use <code>pscl</code> and <code>pROC</code> to find the pseduo-R<sup>2</sup> and AUC of our new model, as well:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AthleteLogisticModel2 &lt;-<span class="st"> </span><span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight <span class="op">*</span><span class="st"> </span>Sex, <span class="dt">data =</span> AthleteEvents, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>) 

pscl<span class="op">::</span><span class="kw">pR2</span>(AthleteLogisticModel2)</code></pre></div>
<pre><code>##           llh       llhNull            G2      McFadden          r2ML 
## -8.413737e+04 -1.130577e+05  5.784073e+04  2.558018e-01  2.446360e-01 
##          r2CU 
##  3.672928e-01</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">LogModel2ROC &lt;-<span class="st"> </span><span class="kw">roc</span>(AthleteLogisticModel2<span class="op">$</span>y, AthleteLogisticModel2<span class="op">$</span>fitted.values)
LogModel2ROC</code></pre></div>
<pre><code>## 
## Call:
## roc.default(response = AthleteLogisticModel2$y, predictor = AthleteLogisticModel2$fitted.values)
## 
## Data: AthleteLogisticModel2$fitted.values in 175984 controls (AthleteLogisticModel2$y 0) &lt; 30181 cases (AthleteLogisticModel2$y 1).
## Area under the curve: 0.6051</code></pre>
<p>So, under each metric, our new model seems to be a slightly better fit to the data. The benefits of working with AUC - and, specifically, with <code>pROC</code> is that testing to see if one model is better than the other is a piece of cake with <code>roc.test</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">roc.test</span>(LogModelROC, LogModel2ROC)</code></pre></div>
<pre><code>## 
##  DeLong&#39;s test for two correlated ROC curves
## 
## data:  LogModelROC and LogModel2ROC
## Z = -21.937, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in AUC is not equal to 0
## sample estimates:
## AUC of roc1 AUC of roc2 
##   0.5752987   0.6051203</code></pre>
<p>And so we’re able to conclude that yes, our second model is significantly better than the first - including sex in our model made it significantly more predictive.</p>
<div id="aic" class="section level3">
<h3><span class="header-section-number">6.8.1</span> AIC</h3>
<p>While comparing model AUCs is effective, it isn’t the most popular method to analyze model performance. That honor likely goes to the Akaike Information Criterion, more commonly known as the AIC. The AIC measures</p>
<p>AIC can be used effectively in three ways:</p>
<ul>
<li><strong>Model selection</strong>, where you compare <em>every combination of scientifically justifiable variables possible</em> OR</li>
<li><strong>Variable analysis</strong> where you either compare your response variable against each predictor variable <em>independently</em> OR</li>
<li><strong>Variable analysis</strong> where you standardize your predictor variables, put them into a model, and compare their coefficients</li>
</ul>
<p>AIC can’t be used to rank random models against one another without actual experimental design. More rants about this may be found <a href="https://dynamicecology.wordpress.com/2015/05/21/why-aic-appeals-to-ecologists-lowest-instincts/">here</a>.</p>
<p>As such, our example here - only comparing two models, with no strong hypothesis as to why these are the two that deserve to be compared - isn’t the best way to demonstrate the use of AIC. We’ll follow up with a more clear example in a moment.</p>
<p>AIC can be calculated using the <code>broom</code> package’s <code>glance()</code> on any model object you have:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(broom)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glance</span>(AthleteLogisticModel)</code></pre></div>
<pre><code>##   null.deviance df.null    logLik      AIC      BIC deviance df.residual
## 1      171694.2  206164 -84851.69 169719.4 169801.3 169703.4      206157</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glance</span>(AthleteLogisticModel2)</code></pre></div>
<pre><code>##   null.deviance df.null    logLik      AIC      BIC deviance df.residual
## 1      171694.2  206164 -84137.37 168306.7 168470.5 168274.7      206149</code></pre>
<p>The number we’re interested in right now is AIC, located halfway across the dataframe. There’s a very simple rule for comparing models using AIC: <span class="math inline">\(\Delta\)</span>AIC between two models &gt; 4? The model with the smaller AIC is better. <span class="math inline">\(\Delta\)</span>AIC between 2 and 4? Odds are the model with the smaller AIC is better, but it’s shakier. <span class="math inline">\(\Delta\)</span>AIC &lt; 2? The two models are effectively identical.</p>
<p>In this case, our second model has an AIC of 168576.3, while the first model’s AIC value is 169872.5. As such, the models have a <span class="math inline">\(\Delta\)</span>AIC of 1296.2, which is a little bit bigger than 4.</p>
<p>Note that the actual AIC number is unitless and arbitrary - the AIC isn’t so much a metric for how well the model fits the data, in the way that R<sup>2</sup> and AUC are, but rather a way to tell <em>which</em> of your models better fits the data. More commonly reported than AIC values are the <span class="math inline">\(\Delta\)</span>AIC values, the number of parameters in a model (represented as <em>k</em>), and the Aikake Weights of each model - information on calculating those <a href="http://www.brianomeara.info/tutorials/aic/">here</a>.</p>
</div>
</div>
<div id="more-complicated-analyses-1" class="section level2">
<h2><span class="header-section-number">6.9</span> More Complicated Analyses</h2>
<p>So far, we haven’t really earned our chapter title - while what we’ve been doing so far has been more in depth, it hasn’t necessarily been more complicated.</p>
<p>This is the section that’ll step things up a little. If you got a strong understanding of functional programming in unit 4, and then understood making your own functions in unit 5, this part shouldn’t be particularly hard. However, it is one of the more involved blocks of code we’ve worked through so far - so don’t feel bad if it takes a little time before things work right, or before you fully understand what we’re doing.</p>
<p>So, as we mentioned above, using AIC to compare two random models isn’t exactly what the tool is designed for. While it isn’t technically <em>wrong</em>, so long as the models are both of the same type (i.e., logistic) and modeling the same dataset, it isn’t <em>useful</em> to science or to you. We don’t particularly care which models are slightly better than others - we want to know which ones are right!</p>
<p>You can either do this by comparing a small set of models that you have strong reasons to believe are accurate - this is a form of hypothesis testing, but using model AICs rather than p values - or by comparing all possible models which use the same set of <em>scientifically sound predictor variables</em>. Note the “scientifically sound” - you can’t throw millions of predictors at the wall and hope that they stick; you have to be able to justify their inclusion.</p>
</div>
<div id="model-selection" class="section level2">
<h2><span class="header-section-number">6.10</span> Model Selection:</h2>
<p>Lets say with our Olympic athlete dataset I can justify expecting sex, age, height, and weight as predictors for the model, as well as the interactions between each of these terms. After all, we can expect age, height, and weight to vary together somewhat - and each of these likely differs between male and female athletes.</p>
<p>One way I could compare the combinations of these variables would be to <code>glance()</code> at each of them individually, like so:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Glancing at the full model
<span class="kw">glance</span>(<span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> AthleteEvents, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>))</code></pre></div>
<pre><code>##   null.deviance df.null    logLik      AIC      BIC deviance df.residual
## 1      171694.2  206164 -84137.37 168306.7 168470.5 168274.7      206149</code></pre>
<p>However, this is inefficient, requires a lot of typing, and makes it really hard to compare AICs directly - or to export them to somewhere like Excel, for inclusion in a document. A somewhat better way is to define each model as its own function, taking the argument <code>df</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">FullMod &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

One &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Two &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Three &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Four &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Height, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Five &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Age, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Six &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Seven &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Eight &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Nine &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Ten &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Eleven &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Twelve &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Age, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Thirteen &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Height, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

Fourteen &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Weight, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}

NullMod &lt;-<span class="st"> </span><span class="cf">function</span>(df){
  <span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> df, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
}</code></pre></div>
<p>That last item in the list is what’s known as the <em>null model</em> - it’s a similar concept to the null hypothesis in hypothesis testing. Its purpose is to serve as a baseline for judging the rest of our models - we’re hoping they have a <span class="math inline">\(\Delta\)</span>AIC &gt; 4!</p>
<p>Now that we have our models defined, we’re able to run each of them against the dataset. Fair warning, this step will take a long time to complete - we’re asking R to compute estimates for something like 4.8 million observations by doing this. We’ll then overwrite the columns we just created, replacing them with the values from <code>glance()</code> so we can make model comparisons:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">LogModelGlances &lt;-<span class="st"> </span>AthleteEvents <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">FullMod =</span> <span class="kw">map</span>(data, FullMod),
         <span class="dt">FullMod =</span> <span class="kw">map</span>(FullMod, glance),
         <span class="dt">One =</span> <span class="kw">map</span>(data, One),
         <span class="dt">One =</span> <span class="kw">map</span>(One, glance),
         <span class="dt">Two =</span> <span class="kw">map</span>(data, Two),
         <span class="dt">Two =</span> <span class="kw">map</span>(Two, glance),
         <span class="dt">Three =</span> <span class="kw">map</span>(data, Three),
         <span class="dt">Three =</span> <span class="kw">map</span>(Three, glance),
         <span class="dt">Four =</span> <span class="kw">map</span>(data, Four),
         <span class="dt">Four =</span> <span class="kw">map</span>(Four, glance),
         <span class="dt">Five =</span> <span class="kw">map</span>(data, Five),
         <span class="dt">Five =</span> <span class="kw">map</span>(Five, glance),
         <span class="dt">Six =</span> <span class="kw">map</span>(data, Six),
         <span class="dt">Six =</span> <span class="kw">map</span>(Six, glance),
         <span class="dt">Seven =</span> <span class="kw">map</span>(data, Seven),
         <span class="dt">Seven =</span> <span class="kw">map</span>(Seven, glance),
         <span class="dt">Eight =</span> <span class="kw">map</span>(data, Eight),
         <span class="dt">Eight =</span> <span class="kw">map</span>(Eight, glance),
         <span class="dt">Nine =</span> <span class="kw">map</span>(data, Nine),
         <span class="dt">Nine =</span> <span class="kw">map</span>(Nine, glance),
         <span class="dt">Ten =</span> <span class="kw">map</span>(data, Ten),
         <span class="dt">Ten =</span> <span class="kw">map</span>(Ten, glance),
         <span class="dt">Eleven =</span> <span class="kw">map</span>(data, Eleven),
         <span class="dt">Eleven =</span> <span class="kw">map</span>(Eleven, glance),
         <span class="dt">Twelve =</span> <span class="kw">map</span>(data, Twelve),
         <span class="dt">Twelve =</span> <span class="kw">map</span>(Twelve, glance),
         <span class="dt">Thirteen =</span> <span class="kw">map</span>(data, Thirteen),
         <span class="dt">Thirteen =</span> <span class="kw">map</span>(Thirteen, glance),
         <span class="dt">Fourteen =</span> <span class="kw">map</span>(data, Fourteen),
         <span class="dt">Fourteen =</span> <span class="kw">map</span>(Fourteen, glance),
         <span class="dt">NullMod =</span> <span class="kw">map</span>(data, NullMod),
         <span class="dt">NullMod =</span> <span class="kw">map</span>(NullMod, glance))

LogModelGlances</code></pre></div>
<pre><code>## # A tibble: 1 x 17
##   data   FullMod  One    Two    Three  Four  Five  Six   Seven Eight Nine 
##   &lt;list&gt; &lt;list&gt;   &lt;list&gt; &lt;list&gt; &lt;list&gt; &lt;lis&gt; &lt;lis&gt; &lt;lis&gt; &lt;lis&gt; &lt;lis&gt; &lt;lis&gt;
## 1 &lt;tibb~ &lt;data.f~ &lt;data~ &lt;data~ &lt;data~ &lt;dat~ &lt;dat~ &lt;dat~ &lt;dat~ &lt;dat~ &lt;dat~
## # ... with 6 more variables: Ten &lt;list&gt;, Eleven &lt;list&gt;, Twelve &lt;list&gt;,
## #   Thirteen &lt;list&gt;, Fourteen &lt;list&gt;, NullMod &lt;list&gt;</code></pre>
<p>(This is why you need to have smart hypotheses about which variables matter - imagine having to wait for thirty-two models to process, or even more!)</p>
<p>We then want to get from this wide dataframe to a tidy dataframe, by <code>gather()</code>ing the model types into a column, paired with the dataframe their column contains:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">LogModelGlances &lt;-<span class="st"> </span>LogModelGlances <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(Model, Value) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">slice</span>(<span class="op">-</span><span class="dv">1</span>)</code></pre></div>
<p>I also used <code>slice(-1)</code> to drop the first row containing our data, since we don’t need it anymore.</p>
<p>Now all that’s left is to unlist our value columns. I’m also going to arrange the table by AIC, to show us which models performed best (and worst!)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">LogModelGlances <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest</span>(Value, <span class="dt">.drop =</span> T) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(AIC)</code></pre></div>
<pre><code>## # A tibble: 16 x 8
##    Model  null.deviance df.null  logLik    AIC    BIC deviance df.residual
##    &lt;chr&gt;          &lt;dbl&gt;   &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt;
##  1 FullM~       171694.  206164 -8.41e4 1.68e5 1.68e5  168275.      206149
##  2 Three        171965.  206852 -8.44e4 1.69e5 1.69e5  168719.      206845
##  3 Seven        171694.  206164 -8.49e4 1.70e5 1.70e5  169703.      206157
##  4 Ten          171965.  206852 -8.51e4 1.70e5 1.70e5  170100.      206849
##  5 Two          172939.  207378 -8.51e4 1.70e5 1.70e5  170118.      207371
##  6 Six          173321.  208240 -8.53e4 1.71e5 1.71e5  170622.      208237
##  7 Nine         172939.  207378 -8.56e4 1.71e5 1.71e5  171265.      207375
##  8 Fourt~       173321.  208240 -8.59e4 1.72e5 1.72e5  171755.      208239
##  9 One          175987.  210067 -8.66e4 1.73e5 1.73e5  173239.      210060
## 10 Four         176348.  210944 -8.69e4 1.74e5 1.74e5  173720.      210941
## 11 Eight        175987.  210067 -8.72e4 1.74e5 1.74e5  174308.      210064
## 12 Thirt~       176348.  210944 -8.74e4 1.75e5 1.75e5  174728.      210943
## 13 Five         220518.  261641 -1.10e5 2.20e5 2.20e5  220249.      261638
## 14 Twelve       220518.  261641 -1.10e5 2.20e5 2.20e5  220370.      261640
## 15 Eleven       226115.  271115 -1.13e5 2.26e5 2.26e5  226101.      271114
## 16 NullM~       226115.  271115 -1.13e5 2.26e5 2.26e5  226115.      271115</code></pre>
<p>Tada! Looks like all our models outperformed the null model by a good margin - and our full model is the best model of the set, with no other model getting particularly close to it. If we wanted, we could now measure just how accurate our best model is, using either AUC or a pseudo-R<sup>2</sup>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ROCMod &lt;-<span class="st"> </span><span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> AthleteEvents, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)

pROC<span class="op">::</span><span class="kw">roc</span>(ROCMod<span class="op">$</span>y, ROCMod<span class="op">$</span>fitted.values)</code></pre></div>
<pre><code>## 
## Call:
## roc.default(response = ROCMod$y, predictor = ROCMod$fitted.values)
## 
## Data: ROCMod$fitted.values in 175984 controls (ROCMod$y 0) &lt; 30181 cases (ROCMod$y 1).
## Area under the curve: 0.6051</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pscl<span class="op">::</span><span class="kw">pR2</span>(<span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> AthleteEvents, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>))</code></pre></div>
<pre><code>##           llh       llhNull            G2      McFadden          r2ML 
## -8.413737e+04 -1.130577e+05  5.784073e+04  2.558018e-01  2.446360e-01 
##          r2CU 
##  3.672928e-01</code></pre>
<p>0.6 AUC and 0.255 McFadden’s pseudo-R<sup>2</sup>. Even after all that, it seems like our model could be improved quite a bit!</p>
<div id="detour-another-way" class="section level3">
<h3><span class="header-section-number">6.10.1</span> Detour: Another Way</h3>
<p>Now, obviously, this entire section breaks our rule that if you have to type it more than twice, there’s a better way. That’s true here, too - but the better way is significantly more complicated, so I introduced the longer form first. The better way is in the next section of this unit.</p>
<p>Typing models out this way does become prohibitive as you add more variables - for every <em>k</em> variables you want to include, you wind up having to type out 2<sup>k</sup> formulas. Even greater than the time tax that puts on you is the amount of time it will take to compute those models and fit them to your data. Generally speaking, you shouldn’t have massive numbers of variables in your regression equations. Remember the old saying:</p>
<blockquote>
<p>All models are wrong, but some models are useful.</p>
</blockquote>
<p>Or, alternately:</p>
<blockquote>
<p>The perfect is the enemy of the pretty good.</p>
</blockquote>
<p>Lots of practicioners want to use as much data as they can to make the most accurate and precise model formula possible, no matter how efficient or practical that formula may be. That’s because a lot of people lose track of the whole purpose of the model - someone should be able to take this crazy thing you’ve created and go <em>do</em> something with it. Models with fifty parameters make that impossible, unless practicioners are going to be able to get as much data as you happened to collect. Plus, longer formulas may be better fits to your data - but they’re also more likely to be <em>overfits</em>, worse at describing the outside world. Finally - and this is the challenge most relevant to business applications, as well - models with more terms are extremely costly to use, requiring either huge amounts of computing power or time to work properly.</p>
<p>As such, a better practice is to figure out which variables are most likely to matter before you start building your models - as we did, with our correlation plots and tables. This method is a lot more sound scientifically, as well - rather than throwing things at the wall until you got one to stick, you’re better able to explain your analysis methods, and the reason those terms matter.</p>
<p>However, if you want to throw things at the wall anyway, the statistically preferred way to do so is stepwise selection (one informative link <a href="https://people.duke.edu/~rnau/regstep.htm">here</a>, another - this one including information on the true “stepwise” bidirectional selection - <a href="https://stats.stackexchange.com/questions/317625/what-is-stepwise-linear-regression">here</a>, and a third - this one explaining things better, but including coding tips for non-R programs, <a href="http://www.markirwin.net/stat135/Lecture/Lecture32.pdf">here</a>).</p>
<p>The basic process to do this is to fit two models - a null model and a full model - and then pass them to the <code>step()</code> function. First, though, we have to drop all the rows where our predictor values have a value of <code>NA</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">StepWiseData &lt;-<span class="st"> </span>AthleteEvents <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">                    </span><span class="kw">drop_na</span>(<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>, <span class="dv">14</span>) ## Numbers specify columns to drop NA in</code></pre></div>
<p>We can choose which type of stepwise selection we want by specifying certain parameters within this function - for instance, given our models:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">StepWiseFullMod &lt;-<span class="st"> </span><span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span>Sex <span class="op">*</span><span class="st"> </span>Age <span class="op">*</span><span class="st"> </span>Height <span class="op">*</span><span class="st"> </span>Weight, <span class="dt">data =</span> StepWiseData, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
StepWiseNullMod &lt;-<span class="st"> </span><span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> StepWiseData, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</code></pre></div>
<p>We can perform a backwards selection by typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">step</span>(StepWiseFullMod)</code></pre></div>
<p>A forward selection via:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">step</span>(StepWiseNullMod, 
     <span class="dt">scope =</span> <span class="kw">list</span>(<span class="dt">lower =</span> <span class="kw">formula</span>(StepWiseNullMod), 
                  <span class="dt">upper =</span> <span class="kw">formula</span>(StepWiseFullMod)),
     <span class="dt">direction =</span> <span class="st">&quot;forward&quot;</span>)</code></pre></div>
<p>And a bi-directional bothways function via the following:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">step</span>(StepWiseNullMod, 
     <span class="dt">scope =</span> <span class="kw">list</span>(<span class="dt">lower =</span> <span class="kw">formula</span>(StepWiseNullMod), 
                  <span class="dt">upper =</span> <span class="kw">formula</span>(StepWiseFullMod)),
     <span class="dt">direction =</span> <span class="st">&quot;both&quot;</span>)</code></pre></div>
<p>I’m not running them here, because they take a ton of space. Note that these methods give us slightly different formulas, due to how each calculates which terms to include.</p>
<p>This method is becoming disfavored, as it doesn’t require you to think about <em>why</em> you want a given variable in the model. But I can’t stop you from doing whatever you’re gonna do.</p>
</div>
<div id="the-better-faster-way" class="section level3">
<h3><span class="header-section-number">6.10.2</span> The Better (…Faster) Way</h3>
<p>Before we launch into this, note that this section is a little more techy and a little more obscure. It shouldn’t be that hard to follow, if you fully understand how for loops and map functions work. But if this is a little above your level right now, that’s totally fine - think of this section as more of a template, showing how we can combine tools to make our code faster and more efficient.</p>
<p>There <em>is</em> a way to programmatically generate all the models, using the <code>map()</code> family of functions. Before we get to that, though, let’s create a smaller dataframe - <code>Predictors</code> - that only contains our predictor variables. We’ll also get the <code>names()</code> of all our predictors, and store that in our column <code>Cols</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Predictors &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Sex =</span> AthleteEvents<span class="op">$</span>Sex,
                         <span class="dt">Age =</span> AthleteEvents<span class="op">$</span>Age,
                         <span class="dt">Height =</span> AthleteEvents<span class="op">$</span>Height,
                         <span class="dt">Weight =</span> AthleteEvents<span class="op">$</span>Weight)

Cols &lt;-<span class="st"> </span><span class="kw">names</span>(Predictors)</code></pre></div>
<p>We’re now going to find the <code>length()</code> of our <code>Cols</code> vector and store it in <code>n</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="kw">length</span>(Cols)</code></pre></div>
<p>Alright, here’s where things get a little more complicated.</p>
<p>What we want to do is use the <code>combn()</code> function to find all the combinations of our variables, so that we can use those to programmatically build formulas. The way we do this is to build what’s known as an <em>anonymous function</em> inside of <code>combn()</code> by typing <code>~</code>, using our <code>.</code> pronoun to iterate through a dataset. We’ll also set <code>simplify</code> inside of the <code>combn()</code> function to <code>FALSE</code>. If we pass this to <code>map()</code>, we get the following output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">map</span>(<span class="dv">1</span><span class="op">:</span>n, <span class="op">~</span><span class="st"> </span><span class="kw">combn</span>(<span class="dv">1</span><span class="op">:</span>n, ., <span class="dt">simplify =</span> <span class="ot">FALSE</span>))</code></pre></div>
<pre><code>## [[1]]
## [[1]][[1]]
## [1] 1
## 
## [[1]][[2]]
## [1] 2
## 
## [[1]][[3]]
## [1] 3
## 
## [[1]][[4]]
## [1] 4
## 
## 
## [[2]]
## [[2]][[1]]
## [1] 1 2
## 
## [[2]][[2]]
## [1] 1 3
## 
## [[2]][[3]]
## [1] 1 4
## 
## [[2]][[4]]
## [1] 2 3
## 
## [[2]][[5]]
## [1] 2 4
## 
## [[2]][[6]]
## [1] 3 4
## 
## 
## [[3]]
## [[3]][[1]]
## [1] 1 2 3
## 
## [[3]][[2]]
## [1] 1 2 4
## 
## [[3]][[3]]
## [1] 1 3 4
## 
## [[3]][[4]]
## [1] 2 3 4
## 
## 
## [[4]]
## [[4]][[1]]
## [1] 1 2 3 4</code></pre>
<p>Which is very close to what we want. The issue is, each of these combinations is buried inside a list - while we want a list of combinations, what we have is a list of lists of combinations. To get rid of that higher-level list, we can use the <code>unlist()</code> function - specifying <code>recursive = FALSE</code> to make sure we only get rid of the top-level list. I’m going to assign that to <code>id</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">id &lt;-<span class="st"> </span><span class="kw">unlist</span>(<span class="kw">map</span>(<span class="dv">1</span><span class="op">:</span>n, <span class="op">~</span><span class="st"> </span><span class="kw">combn</span>(<span class="dv">1</span><span class="op">:</span>n, ., <span class="dt">simplify =</span> <span class="ot">FALSE</span>)), <span class="dt">recursive =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p>We now have everything we need to find our formulas - the names of our predictor variables and all the combinations we want of them. We’re now going to use <code>map_chr()</code> to <code>paste()</code> together each of our formulas - by indexing <code>Cols</code> with <code>[.]</code> in our anonymous function, we can call each combination of column names we have specified in <code>id</code>. <code>collapse = &quot;*&quot;</code> will separate each of our predictors with the <code>*</code> operator:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Formulas &lt;-<span class="st"> </span><span class="kw">map_chr</span>(id, <span class="op">~</span><span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;Winner ~&quot;</span>, <span class="kw">paste</span>(Cols[.], <span class="dt">collapse=</span><span class="st">&quot;*&quot;</span>)))
Formulas</code></pre></div>
<pre><code>##  [1] &quot;Winner ~ Sex&quot;                   &quot;Winner ~ Age&quot;                  
##  [3] &quot;Winner ~ Height&quot;                &quot;Winner ~ Weight&quot;               
##  [5] &quot;Winner ~ Sex*Age&quot;               &quot;Winner ~ Sex*Height&quot;           
##  [7] &quot;Winner ~ Sex*Weight&quot;            &quot;Winner ~ Age*Height&quot;           
##  [9] &quot;Winner ~ Age*Weight&quot;            &quot;Winner ~ Height*Weight&quot;        
## [11] &quot;Winner ~ Sex*Age*Height&quot;        &quot;Winner ~ Sex*Age*Weight&quot;       
## [13] &quot;Winner ~ Sex*Height*Weight&quot;     &quot;Winner ~ Age*Height*Weight&quot;    
## [15] &quot;Winner ~ Sex*Age*Height*Weight&quot;</code></pre>
<p>Now, my desired outputs here are two dataframes: one of the outputs from <code>tidy()</code>, and one of the outputs from <code>glance()</code>. As such, I’m going to initalize two dataframes, <code>Glances</code> and <code>Tidies</code>, with the outputs from those functions. I’m also going to create a column in <code>Tidies</code> to store which formula the output is from:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Glances &lt;-<span class="st"> </span><span class="kw">glance</span>(<span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> AthleteEvents, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>))
Tidies &lt;-<span class="st"> </span><span class="kw">tidy</span>(<span class="kw">glm</span>(Winner <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> AthleteEvents, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>))
Tidies<span class="op">$</span>FormNum &lt;-<span class="st"> </span><span class="dv">0</span></code></pre></div>
<p>And now we want to actually calculate these models for our data. For this, we have to use a for loop, running as many times as we have formulas. Rather than explain everything in the loop up here, I’ve commented the code below:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span>(i <span class="cf">in</span> <span class="kw">seq_along</span>(Formulas)){
## Convert the current (index i) formula into a logistic model
  CurrentModel &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="kw">as.formula</span>(Formulas[[i]]), <span class="dt">data =</span> AthleteEvents, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
  
## Store the glance of the current model in CurrentGlance
  CurrentGlance &lt;-<span class="st"> </span><span class="kw">glance</span>(CurrentModel)
  
## Make row i of Glances the current model&#39;s glance
  Glances[i, ] &lt;-<span class="st">  </span><span class="kw">as.vector</span>(CurrentGlance)
  
## Store the tidy of the current model, label it with the model number, and convert it to a vector
  CurrentTidy &lt;-<span class="st"> </span><span class="kw">tidy</span>(CurrentModel)
  CurrentTidy<span class="op">$</span>FormNum &lt;-<span class="st"> </span>i
  CurrentTidy &lt;-<span class="st"> </span><span class="kw">as.vector</span>(CurrentTidy)
## Append the current tidy to your table with all tidy outputs
  Tidies &lt;-<span class="st">  </span><span class="kw">rbind</span>(Tidies, CurrentTidy)
}</code></pre></div>
<p>And if everything worked properly, we can print out our dataframes to make sure we got everything right:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Glances</code></pre></div>
<pre><code>##    null.deviance df.null     logLik      AIC      BIC deviance df.residual
## 1       226115.5  271115 -113050.31 226104.6 226125.6 226100.6      271114
## 2       220518.2  261641 -110184.96 220373.9 220394.9 220369.9      261640
## 3       176348.0  210944  -87363.78 174731.6 174752.1 174727.6      210943
## 4       173321.1  208240  -85877.53 171759.1 171779.5 171755.1      208239
## 5       220518.2  261641 -110124.47 220256.9 220298.8 220248.9      261638
## 6       176348.0  210944  -86860.23 173728.5 173769.5 173720.5      210941
## 7       173321.1  208240  -85310.91 170629.8 170670.8 170621.8      208237
## 8       175987.3  210067  -87154.19 174316.4 174357.4 174308.4      210064
## 9       172938.8  207378  -85632.43 171272.9 171313.8 171264.9      207375
## 10      171964.6  206852  -85050.08 170108.2 170149.1 170100.2      206849
## 11      175987.3  210067  -86619.28 173254.6 173336.6 173238.6      210060
## 12      172938.8  207378  -85059.12 170134.2 170216.2 170118.2      207371
## 13      171964.6  206852  -84359.50 168735.0 168816.9 168719.0      206845
## 14      171694.2  206164  -84851.69 169719.4 169801.3 169703.4      206157
## 15      171694.2  206164  -84137.37 168306.7 168470.5 168274.7      206149</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Tidies</code></pre></div>
<pre><code>##                      term      estimate    std.error    statistic
## 1             (Intercept) -1.760419e+00 5.427627e-03 -324.3440545
## 2             (Intercept) -1.726761e+00 1.023087e-02 -168.7794466
## 3                    SexM -4.662798e-02 1.206945e-02   -3.8633054
## 4             (Intercept) -2.002166e+00 2.203888e-02  -90.8470032
## 5                     Age  1.018106e-02 8.256062e-04   12.3316206
## 6             (Intercept) -5.918769e+00 1.046610e-01  -56.5518317
## 7                  Height  2.361839e-02 5.897656e-04   40.0470833
## 8             (Intercept) -2.949270e+00 3.068582e-02  -96.1118341
## 9                  Weight  1.647833e-02 4.109985e-04   40.0933962
## 10            (Intercept) -2.337555e+00 4.189197e-02  -55.7995954
## 11                   SexM  4.316677e-01 4.966264e-02    8.6920015
## 12                    Age  2.561744e-02 1.668813e-03   15.3506922
## 13               SexM:Age -1.962561e-02 1.934180e-03  -10.1467317
## 14            (Intercept) -8.664980e+00 2.117938e-01  -40.9123457
## 15                   SexM  1.377806e+00 2.573728e-01    5.3533491
## 16                 Height  4.128154e-02 1.244678e-03   33.1664401
## 17            SexM:Height -1.069198e-02 1.483950e-03   -7.2050810
## 18            (Intercept) -3.748930e+00 6.308936e-02  -59.4225448
## 19                   SexM  3.189663e-01 7.616761e-02    4.1876899
## 20                 Weight  3.355064e-02 9.979865e-04   33.6183304
## 21            SexM:Weight -1.237687e-02 1.132612e-03  -10.9277252
## 22            (Intercept) -7.046795e+00 4.884235e-01  -14.4276321
## 23                    Age  5.015113e-02 1.930937e-02    2.5972431
## 24                 Height  2.873441e-02 2.782735e-03   10.3259586
## 25             Age:Height -2.325052e-04 1.097831e-04   -2.1178594
## 26            (Intercept) -4.372707e+00 1.440723e-01  -30.3507721
## 27                    Age  5.759834e-02 5.586608e-03   10.3100725
## 28                 Weight  3.442307e-02 1.983683e-03   17.3531124
## 29             Age:Weight -7.199431e-04 7.593994e-05   -9.4804283
## 30            (Intercept) -2.143225e+00 4.084826e-01   -5.2467958
## 31                 Height -9.128709e-04 2.340481e-03   -0.3900355
## 32                 Weight -3.365387e-02 5.727336e-03   -5.8760081
## 33          Height:Weight  2.310796e-04 3.124574e-05    7.3955546
## 34            (Intercept) -9.601547e+00 9.348757e-01  -10.2704002
## 35                   SexM  3.439781e+00 1.196796e+00    2.8741587
## 36                    Age  5.158874e-02 3.842412e-02    1.3426135
## 37                 Height  4.374157e-02 5.550280e-03    7.8809667
## 38               SexM:Age -9.306460e-02 4.789933e-02   -1.9429205
## 39            SexM:Height -2.056115e-02 6.935091e-03   -2.9647990
## 40             Age:Height -1.772303e-04 2.276361e-04   -0.7785684
## 41        SexM:Age:Height  4.535119e-04 2.777614e-04    1.6327391
## 42            (Intercept) -5.141523e+00 2.800272e-01  -18.3607979
## 43                   SexM  3.473694e-01 3.573439e-01    0.9720872
## 44                    Age  6.214581e-02 1.129033e-02    5.5043404
## 45                 Weight  4.884645e-02 4.571811e-03   10.6842689
## 46               SexM:Age -9.297458e-03 1.404514e-02   -0.6619697
## 47            SexM:Weight -1.040079e-02 5.374259e-03   -1.9352974
## 48             Age:Weight -7.016833e-04 1.824728e-04   -3.8454122
## 49        SexM:Age:Weight  3.762839e-05 2.108204e-04    0.1784856
## 50            (Intercept) -5.587619e+00 9.500164e-01   -5.8816024
## 51                   SexM  4.308620e+00 1.165394e+00    3.6971366
## 52                 Height  1.615014e-02 5.616214e-03    2.8756281
## 53                 Weight -6.006362e-03 1.537451e-02   -0.3906701
## 54            SexM:Height -2.398652e-02 6.750308e-03   -3.5533962
## 55            SexM:Weight -4.566430e-02 1.764738e-02   -2.5875963
## 56          Height:Weight  1.471334e-04 8.844558e-05    1.6635474
## 57     SexM:Height:Weight  2.016674e-04 1.000507e-04    2.0156524
## 58            (Intercept) -4.023117e+00 1.815347e+00   -2.2161699
## 59                    Age  1.227940e-01 7.357736e-02    1.6689100
## 60                 Height -2.067333e-03 1.061676e-02   -0.1947234
## 61                 Weight  3.083361e-02 2.615719e-02    1.1787816
## 62             Age:Height -2.260540e-04 4.275407e-04   -0.5287310
## 63             Age:Weight -3.098892e-03 1.036319e-03   -2.9902867
## 64          Height:Weight  1.594749e-05 1.447030e-04    0.1102084
## 65      Age:Height:Weight  1.159619e-05 5.730893e-06    2.0234520
## 66            (Intercept)  1.527533e+01 3.899956e+00    3.9167947
## 67                   SexM -6.818958e+00 5.312396e+00   -1.2835938
## 68                    Age -8.418150e-01 1.723239e-01   -4.8850741
## 69                 Height -1.135306e-01 2.352660e-02   -4.8256257
## 70                 Weight -3.703604e-01 6.492167e-02   -5.7047273
## 71               SexM:Age  4.670132e-01 2.215298e-01    2.1081278
## 72            SexM:Height  3.795323e-02 3.097937e-02    1.2251131
## 73             Age:Height  5.251190e-03 1.030328e-03    5.0966212
## 74            SexM:Weight  2.699587e-01 7.976007e-02    3.3846349
## 75             Age:Weight  1.460616e-02 2.790005e-03    5.2351737
## 76          Height:Weight  2.346084e-03 3.797527e-04    6.1779257
## 77        SexM:Age:Height -2.645045e-03 1.290586e-03   -2.0494915
## 78        SexM:Age:Weight -1.270139e-02 3.303472e-03   -3.8448615
## 79     SexM:Height:Weight -1.561545e-03 4.561802e-04   -3.4230881
## 80      Age:Height:Weight -8.842913e-05 1.627946e-05   -5.4319432
## 81 SexM:Age:Height:Weight  7.155419e-05 1.892650e-05    3.7806348
##          p.value FormNum
## 1   0.000000e+00       0
## 2   0.000000e+00       1
## 3   1.118630e-04       1
## 4   0.000000e+00       2
## 5   6.120327e-35       2
## 6   0.000000e+00       3
## 7   0.000000e+00       3
## 8   0.000000e+00       4
## 9   0.000000e+00       4
## 10  0.000000e+00       5
## 11  3.561093e-18       5
## 12  3.504271e-53       5
## 13  3.426465e-24       5
## 14  0.000000e+00       6
## 15  8.634105e-08       6
## 16 3.281816e-241       6
## 17  5.800935e-13       6
## 18  0.000000e+00       7
## 19  2.818082e-05       7
## 20 9.054728e-248       7
## 21  8.495133e-28       7
## 22  3.467836e-47       8
## 23  9.397538e-03       8
## 24  5.377890e-25       8
## 25  3.418698e-02       8
## 26 2.454218e-202       9
## 27  6.345343e-25       9
## 28  1.868411e-67       9
## 29  2.532415e-21       9
## 30  1.547673e-07      10
## 31  6.965103e-01      10
## 32  4.202777e-09      10
## 33  1.408193e-13      10
## 34  9.580640e-25      11
## 35  4.051054e-03      11
## 36  1.793971e-01      11
## 37  3.248578e-15      11
## 38  5.202576e-02      11
## 39  3.028807e-03      11
## 40  4.362340e-01      11
## 41  1.025239e-01      11
## 42  2.706018e-75      12
## 43  3.310072e-01      12
## 44  3.705529e-08      12
## 45  1.205955e-26      12
## 46  5.079907e-01      12
## 47  5.295381e-02      12
## 48  1.203500e-04      12
## 49  8.583416e-01      12
## 50  4.063135e-09      13
## 51  2.180450e-04      13
## 52  4.032245e-03      13
## 53  6.960411e-01      13
## 54  3.802912e-04      13
## 55  9.664817e-03      13
## 56  9.620291e-02      13
## 57  4.383634e-02      13
## 58  2.667987e-02      14
## 59  9.513521e-02      14
## 60  8.456095e-01      14
## 61  2.384852e-01      14
## 62  5.969921e-01      14
## 63  2.787157e-03      14
## 64  9.122441e-01      14
## 65  4.302656e-02      14
## 66  8.973410e-05      15
## 67  1.992841e-01      15
## 68  1.033899e-06      15
## 69  1.395644e-06      15
## 70  1.165295e-08      15
## 71  3.501994e-02      15
## 72  2.205326e-01      15
## 73  3.457693e-07      15
## 74  7.127299e-04      15
## 75  1.648298e-07      15
## 76  6.494925e-10      15
## 77  4.041408e-02      15
## 78  1.206206e-04      15
## 79  6.191401e-04      15
## 80  5.574367e-08      15
## 81  1.564290e-04      15</code></pre>
</div>
</div>
<div id="relational-data" class="section level2">
<h2><span class="header-section-number">6.11</span> Relational Data</h2>
<p>Okay, this next section should be easier and more relevant to your daily life. Before we get into it, I’m going to make two edits to the <code>Glances</code> table:</p>
<ol style="list-style-type: decimal">
<li>I’m going to convert the row names (those unlabeled numbers on the left) into a column called <code>FormNum</code></li>
<li>I’m going to only select our columns of <code>FormNum</code> and <code>AIC</code>:</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Glances &lt;-<span class="st"> </span>Glances <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">FormNum =</span> <span class="kw">as.numeric</span>(<span class="kw">row.names</span>(.))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(FormNum, AIC)
Glances</code></pre></div>
<pre><code>##    FormNum      AIC
## 1        1 226104.6
## 2        2 220373.9
## 3        3 174731.6
## 4        4 171759.1
## 5        5 220256.9
## 6        6 173728.5
## 7        7 170629.8
## 8        8 174316.4
## 9        9 171272.9
## 10      10 170108.2
## 11      11 173254.6
## 12      12 170134.2
## 13      13 168735.0
## 14      14 169719.4
## 15      15 168306.7</code></pre>
<p>I also want to point out one important difference between our dataframes - the <code>Glances</code> dataframe doesn’t include our null model, while <code>Tidies</code> has it as <code>FormNum == 0</code>. We can check to make sure by <code>factor()</code>ing our dataframes’ <code>FormNum</code> fields, which identifies each unique level in the vector. We can then find all the <code>levels()</code> contained in that factor:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">levels</span>(<span class="kw">factor</span>(Glances<span class="op">$</span>FormNum))</code></pre></div>
<pre><code>##  [1] &quot;1&quot;  &quot;2&quot;  &quot;3&quot;  &quot;4&quot;  &quot;5&quot;  &quot;6&quot;  &quot;7&quot;  &quot;8&quot;  &quot;9&quot;  &quot;10&quot; &quot;11&quot; &quot;12&quot; &quot;13&quot; &quot;14&quot;
## [15] &quot;15&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">levels</span>(<span class="kw">factor</span>(Tidies<span class="op">$</span>FormNum))</code></pre></div>
<pre><code>##  [1] &quot;0&quot;  &quot;1&quot;  &quot;2&quot;  &quot;3&quot;  &quot;4&quot;  &quot;5&quot;  &quot;6&quot;  &quot;7&quot;  &quot;8&quot;  &quot;9&quot;  &quot;10&quot; &quot;11&quot; &quot;12&quot; &quot;13&quot;
## [15] &quot;14&quot; &quot;15&quot;</code></pre>
<p>Inner Join</p>
<p>Left Join</p>
<p>Right Join</p>
<p>Full Join</p>
<p>by =</p>
<p>Semi Join</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">BestMods &lt;-<span class="st"> </span>Glances <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(AIC <span class="op">&lt;</span><span class="st"> </span><span class="kw">min</span>(AIC) <span class="op">+</span><span class="st"> </span><span class="dv">4</span>)
BestMods</code></pre></div>
<pre><code>##   FormNum      AIC
## 1      15 168306.7</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">semi_join</span>(Tidies, BestMods)</code></pre></div>
<pre><code>## Joining, by = &quot;FormNum&quot;</code></pre>
<pre><code>##                      term      estimate    std.error statistic
## 1             (Intercept)  1.527533e+01 3.899956e+00  3.916795
## 2                    SexM -6.818958e+00 5.312396e+00 -1.283594
## 3                     Age -8.418150e-01 1.723239e-01 -4.885074
## 4                  Height -1.135306e-01 2.352660e-02 -4.825626
## 5                  Weight -3.703604e-01 6.492167e-02 -5.704727
## 6                SexM:Age  4.670132e-01 2.215298e-01  2.108128
## 7             SexM:Height  3.795323e-02 3.097937e-02  1.225113
## 8              Age:Height  5.251190e-03 1.030328e-03  5.096621
## 9             SexM:Weight  2.699587e-01 7.976007e-02  3.384635
## 10             Age:Weight  1.460616e-02 2.790005e-03  5.235174
## 11          Height:Weight  2.346084e-03 3.797527e-04  6.177926
## 12        SexM:Age:Height -2.645045e-03 1.290586e-03 -2.049491
## 13        SexM:Age:Weight -1.270139e-02 3.303472e-03 -3.844861
## 14     SexM:Height:Weight -1.561545e-03 4.561802e-04 -3.423088
## 15      Age:Height:Weight -8.842913e-05 1.627946e-05 -5.431943
## 16 SexM:Age:Height:Weight  7.155419e-05 1.892650e-05  3.780635
##         p.value FormNum
## 1  8.973410e-05      15
## 2  1.992841e-01      15
## 3  1.033899e-06      15
## 4  1.395644e-06      15
## 5  1.165295e-08      15
## 6  3.501994e-02      15
## 7  2.205326e-01      15
## 8  3.457693e-07      15
## 9  7.127299e-04      15
## 10 1.648298e-07      15
## 11 6.494925e-10      15
## 12 4.041408e-02      15
## 13 1.206206e-04      15
## 14 6.191401e-04      15
## 15 5.574367e-08      15
## 16 1.564290e-04      15</code></pre>
<p>Anti Join</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anti_join</span>(Tidies, BestMods)</code></pre></div>
<pre><code>## Joining, by = &quot;FormNum&quot;</code></pre>
<pre><code>##                  term      estimate    std.error    statistic
## 1         (Intercept) -1.760419e+00 5.427627e-03 -324.3440545
## 2         (Intercept) -1.726761e+00 1.023087e-02 -168.7794466
## 3                SexM -4.662798e-02 1.206945e-02   -3.8633054
## 4         (Intercept) -2.002166e+00 2.203888e-02  -90.8470032
## 5                 Age  1.018106e-02 8.256062e-04   12.3316206
## 6         (Intercept) -5.918769e+00 1.046610e-01  -56.5518317
## 7              Height  2.361839e-02 5.897656e-04   40.0470833
## 8         (Intercept) -2.949270e+00 3.068582e-02  -96.1118341
## 9              Weight  1.647833e-02 4.109985e-04   40.0933962
## 10        (Intercept) -2.337555e+00 4.189197e-02  -55.7995954
## 11               SexM  4.316677e-01 4.966264e-02    8.6920015
## 12                Age  2.561744e-02 1.668813e-03   15.3506922
## 13           SexM:Age -1.962561e-02 1.934180e-03  -10.1467317
## 14        (Intercept) -8.664980e+00 2.117938e-01  -40.9123457
## 15               SexM  1.377806e+00 2.573728e-01    5.3533491
## 16             Height  4.128154e-02 1.244678e-03   33.1664401
## 17        SexM:Height -1.069198e-02 1.483950e-03   -7.2050810
## 18        (Intercept) -3.748930e+00 6.308936e-02  -59.4225448
## 19               SexM  3.189663e-01 7.616761e-02    4.1876899
## 20             Weight  3.355064e-02 9.979865e-04   33.6183304
## 21        SexM:Weight -1.237687e-02 1.132612e-03  -10.9277252
## 22        (Intercept) -7.046795e+00 4.884235e-01  -14.4276321
## 23                Age  5.015113e-02 1.930937e-02    2.5972431
## 24             Height  2.873441e-02 2.782735e-03   10.3259586
## 25         Age:Height -2.325052e-04 1.097831e-04   -2.1178594
## 26        (Intercept) -4.372707e+00 1.440723e-01  -30.3507721
## 27                Age  5.759834e-02 5.586608e-03   10.3100725
## 28             Weight  3.442307e-02 1.983683e-03   17.3531124
## 29         Age:Weight -7.199431e-04 7.593994e-05   -9.4804283
## 30        (Intercept) -2.143225e+00 4.084826e-01   -5.2467958
## 31             Height -9.128709e-04 2.340481e-03   -0.3900355
## 32             Weight -3.365387e-02 5.727336e-03   -5.8760081
## 33      Height:Weight  2.310796e-04 3.124574e-05    7.3955546
## 34        (Intercept) -9.601547e+00 9.348757e-01  -10.2704002
## 35               SexM  3.439781e+00 1.196796e+00    2.8741587
## 36                Age  5.158874e-02 3.842412e-02    1.3426135
## 37             Height  4.374157e-02 5.550280e-03    7.8809667
## 38           SexM:Age -9.306460e-02 4.789933e-02   -1.9429205
## 39        SexM:Height -2.056115e-02 6.935091e-03   -2.9647990
## 40         Age:Height -1.772303e-04 2.276361e-04   -0.7785684
## 41    SexM:Age:Height  4.535119e-04 2.777614e-04    1.6327391
## 42        (Intercept) -5.141523e+00 2.800272e-01  -18.3607979
## 43               SexM  3.473694e-01 3.573439e-01    0.9720872
## 44                Age  6.214581e-02 1.129033e-02    5.5043404
## 45             Weight  4.884645e-02 4.571811e-03   10.6842689
## 46           SexM:Age -9.297458e-03 1.404514e-02   -0.6619697
## 47        SexM:Weight -1.040079e-02 5.374259e-03   -1.9352974
## 48         Age:Weight -7.016833e-04 1.824728e-04   -3.8454122
## 49    SexM:Age:Weight  3.762839e-05 2.108204e-04    0.1784856
## 50        (Intercept) -5.587619e+00 9.500164e-01   -5.8816024
## 51               SexM  4.308620e+00 1.165394e+00    3.6971366
## 52             Height  1.615014e-02 5.616214e-03    2.8756281
## 53             Weight -6.006362e-03 1.537451e-02   -0.3906701
## 54        SexM:Height -2.398652e-02 6.750308e-03   -3.5533962
## 55        SexM:Weight -4.566430e-02 1.764738e-02   -2.5875963
## 56      Height:Weight  1.471334e-04 8.844558e-05    1.6635474
## 57 SexM:Height:Weight  2.016674e-04 1.000507e-04    2.0156524
## 58        (Intercept) -4.023117e+00 1.815347e+00   -2.2161699
## 59                Age  1.227940e-01 7.357736e-02    1.6689100
## 60             Height -2.067333e-03 1.061676e-02   -0.1947234
## 61             Weight  3.083361e-02 2.615719e-02    1.1787816
## 62         Age:Height -2.260540e-04 4.275407e-04   -0.5287310
## 63         Age:Weight -3.098892e-03 1.036319e-03   -2.9902867
## 64      Height:Weight  1.594749e-05 1.447030e-04    0.1102084
## 65  Age:Height:Weight  1.159619e-05 5.730893e-06    2.0234520
##          p.value FormNum
## 1   0.000000e+00       0
## 2   0.000000e+00       1
## 3   1.118630e-04       1
## 4   0.000000e+00       2
## 5   6.120327e-35       2
## 6   0.000000e+00       3
## 7   0.000000e+00       3
## 8   0.000000e+00       4
## 9   0.000000e+00       4
## 10  0.000000e+00       5
## 11  3.561093e-18       5
## 12  3.504271e-53       5
## 13  3.426465e-24       5
## 14  0.000000e+00       6
## 15  8.634105e-08       6
## 16 3.281816e-241       6
## 17  5.800935e-13       6
## 18  0.000000e+00       7
## 19  2.818082e-05       7
## 20 9.054728e-248       7
## 21  8.495133e-28       7
## 22  3.467836e-47       8
## 23  9.397538e-03       8
## 24  5.377890e-25       8
## 25  3.418698e-02       8
## 26 2.454218e-202       9
## 27  6.345343e-25       9
## 28  1.868411e-67       9
## 29  2.532415e-21       9
## 30  1.547673e-07      10
## 31  6.965103e-01      10
## 32  4.202777e-09      10
## 33  1.408193e-13      10
## 34  9.580640e-25      11
## 35  4.051054e-03      11
## 36  1.793971e-01      11
## 37  3.248578e-15      11
## 38  5.202576e-02      11
## 39  3.028807e-03      11
## 40  4.362340e-01      11
## 41  1.025239e-01      11
## 42  2.706018e-75      12
## 43  3.310072e-01      12
## 44  3.705529e-08      12
## 45  1.205955e-26      12
## 46  5.079907e-01      12
## 47  5.295381e-02      12
## 48  1.203500e-04      12
## 49  8.583416e-01      12
## 50  4.063135e-09      13
## 51  2.180450e-04      13
## 52  4.032245e-03      13
## 53  6.960411e-01      13
## 54  3.802912e-04      13
## 55  9.664817e-03      13
## 56  9.620291e-02      13
## 57  4.383634e-02      13
## 58  2.667987e-02      14
## 59  9.513521e-02      14
## 60  8.456095e-01      14
## 61  2.384852e-01      14
## 62  5.969921e-01      14
## 63  2.787157e-03      14
## 64  9.122441e-01      14
## 65  4.302656e-02      14</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="functions-and-scripting.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="achieving-graphical-excellence.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
